// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.Repository;

#nullable disable

namespace Sistema.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20260324161654_RelacionandoFotosCorretamente")]
    partial class RelacionandoFotosCorretamente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sistema.Modelos.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Localizacao")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RelatorioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatorioId");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("Sistema.Modelos.Relatorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TerrenoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerrenoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("Sistema.Modelos.Terrenos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Proprietaria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Terrenos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 5000m,
                            Cidade = "Joinville",
                            Matricula = 767375,
                            Nome = "Casa do Baixo Quiriri",
                            Proprietaria = "Hacasa"
                        },
                        new
                        {
                            Id = 2,
                            Area = 10000m,
                            Cidade = "Campo alegre",
                            Matricula = 6537523,
                            Nome = "Casa do Alto Quiriri",
                            Proprietaria = "Ciser"
                        },
                        new
                        {
                            Id = 3,
                            Area = 1000m,
                            Cidade = "Sao Francisco do Sul",
                            Matricula = 59375237,
                            Nome = "Terreno Loteamento Espinheiro",
                            Proprietaria = "Hacasa"
                        },
                        new
                        {
                            Id = 4,
                            Area = 5000m,
                            Cidade = "Joinville",
                            Matricula = 837539,
                            Nome = "Terreno Loteamento Boa Vista",
                            Proprietaria = "Ciser"
                        },
                        new
                        {
                            Id = 5,
                            Area = 100m,
                            Cidade = "Sao Francisco do Sul",
                            Matricula = 31398375,
                            Nome = "Terreno Loteamento America",
                            Proprietaria = "Ciser"
                        },
                        new
                        {
                            Id = 6,
                            Area = 50000m,
                            Cidade = "Campo alegre",
                            Matricula = 2697867,
                            Nome = "Chacara Campo Alegre",
                            Proprietaria = "Parana"
                        },
                        new
                        {
                            Id = 7,
                            Area = 8000m,
                            Cidade = "Joinville",
                            Matricula = 1785,
                            Nome = "Sede Ciser",
                            Proprietaria = "Hacasa"
                        });
                });

            modelBuilder.Entity("Sistema.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistema.Modelos.Foto", b =>
                {
                    b.HasOne("Sistema.Modelos.Relatorios", "Relatorios")
                        .WithMany("Fotos")
                        .HasForeignKey("RelatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("Sistema.Modelos.Relatorios", b =>
                {
                    b.HasOne("Sistema.Modelos.Terrenos", "Terreno")
                        .WithMany()
                        .HasForeignKey("TerrenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terreno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema.Modelos.Relatorios", b =>
                {
                    b.Navigation("Fotos");
                });
#pragma warning restore 612, 618
        }
    }
}
