// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.repository;

#nullable disable

namespace Sistema.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20260310203919_AdicionarTabelaTerrenos")]
    partial class AdicionarTabelaTerrenos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sistema.Modelos.Terrenos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("Matricula")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Proprietaria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Terrenos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Area = 5000m,
                            Matricula = 7L,
                            Nome = "Casa do Baixo Quiriri",
                            Proprietaria = "Hacasa"
                        },
                        new
                        {
                            Id = 2L,
                            Area = 10000m,
                            Matricula = 6L,
                            Nome = "Casa do Alto Quiriri",
                            Proprietaria = "Ciser"
                        },
                        new
                        {
                            Id = 3L,
                            Area = 1000m,
                            Matricula = 5L,
                            Nome = "Terreno Loteamento Espinheiro",
                            Proprietaria = "Hacasa"
                        },
                        new
                        {
                            Id = 4L,
                            Area = 5000m,
                            Matricula = 8L,
                            Nome = "Terreno Loteamento Boa Vista",
                            Proprietaria = "Ciser"
                        },
                        new
                        {
                            Id = 5L,
                            Area = 100m,
                            Matricula = 3L,
                            Nome = "Terreno Loteamento America",
                            Proprietaria = "Ciser"
                        },
                        new
                        {
                            Id = 6L,
                            Area = 50000m,
                            Matricula = 2L,
                            Nome = "Chacara Campo Alegre",
                            Proprietaria = "Parana"
                        },
                        new
                        {
                            Id = 7L,
                            Area = 8000m,
                            Matricula = 1L,
                            Nome = "Sede Ciser",
                            Proprietaria = "Hacasa"
                        });
                });

            modelBuilder.Entity("Sistema.modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
