// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema.Repository;

#nullable disable

namespace Sistema.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    partial class MeuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sistema.Modelos.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataFoto")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RelatorioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatorioId");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("Sistema.Modelos.Relatorios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TerrenoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TerrenoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("Sistema.Modelos.Terrenos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Matricula")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Proprietaria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Terrenos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 5000m,
                            Cidade = "Joinville",
                            Matricula = 767375,
                            Nome = "Casa do Baixo Quiriri",
                            Proprietaria = "Hacasa"
                        },
                        new
                        {
                            Id = 2,
                            Area = 10000m,
                            Cidade = "Campo alegre",
                            Matricula = 6537523,
                            Nome = "Casa do Alto Quiriri",
                            Proprietaria = "Ciser"
                        },
                        new
                        {
                            Id = 3,
                            Area = 1000m,
                            Cidade = "Sao Francisco do Sul",
                            Matricula = 59375237,
                            Nome = "Terreno Loteamento Espinheiro",
                            Proprietaria = "Hacasa"
                        },
                        new
                        {
                            Id = 4,
                            Area = 5000m,
                            Cidade = "Joinville",
                            Matricula = 837539,
                            Nome = "Terreno Loteamento Boa Vista",
                            Proprietaria = "Ciser"
                        },
                        new
                        {
                            Id = 5,
                            Area = 100m,
                            Cidade = "Sao Francisco do Sul",
                            Matricula = 31398375,
                            Nome = "Terreno Loteamento America",
                            Proprietaria = "Ciser"
                        },
                        new
                        {
                            Id = 6,
                            Area = 50000m,
                            Cidade = "Campo alegre",
                            Matricula = 2697867,
                            Nome = "Chacara Campo Alegre",
                            Proprietaria = "Parana"
                        },
                        new
                        {
                            Id = 7,
                            Area = 8000m,
                            Cidade = "Joinville",
                            Matricula = 1785,
                            Nome = "Sede Ciser",
                            Proprietaria = "Hacasa"
                        },
                        new
                        {
                            Id = 8,
                            Area = 12000m,
                            Cidade = "Londrina",
                            Matricula = 2451,
                            Nome = "Fazenda Boa Vista",
                            Proprietaria = "AgroSul"
                        },
                        new
                        {
                            Id = 9,
                            Area = 4500m,
                            Cidade = "Maringá",
                            Matricula = 3124,
                            Nome = "Sítio Recanto Verde",
                            Proprietaria = "VerdeVale"
                        },
                        new
                        {
                            Id = 10,
                            Area = 3000m,
                            Cidade = "Curitiba",
                            Matricula = 1987,
                            Nome = "Chácara Santa Luzia",
                            Proprietaria = "Família Souza"
                        },
                        new
                        {
                            Id = 11,
                            Area = 25000m,
                            Cidade = "Campo Grande",
                            Matricula = 5562,
                            Nome = "Fazenda Horizonte",
                            Proprietaria = "TerraNova"
                        },
                        new
                        {
                            Id = 12,
                            Area = 5200m,
                            Cidade = "Guarapuava",
                            Matricula = 2874,
                            Nome = "Sítio Bela Serra",
                            Proprietaria = "SerraAlta"
                        },
                        new
                        {
                            Id = 13,
                            Area = 3800m,
                            Cidade = "Ponta Grossa",
                            Matricula = 3345,
                            Nome = "Chácara Vale do Sol",
                            Proprietaria = "ValeSul"
                        },
                        new
                        {
                            Id = 14,
                            Area = 18000m,
                            Cidade = "Cascavel",
                            Matricula = 6721,
                            Nome = "Fazenda Três Rios",
                            Proprietaria = "AgroRios"
                        },
                        new
                        {
                            Id = 15,
                            Area = 6100m,
                            Cidade = "Blumenau",
                            Matricula = 4210,
                            Nome = "Sítio Pedra Branca",
                            Proprietaria = "PedraSul"
                        },
                        new
                        {
                            Id = 16,
                            Area = 2900m,
                            Cidade = "Florianópolis",
                            Matricula = 3891,
                            Nome = "Chácara Primavera",
                            Proprietaria = "Primavera Ltda"
                        },
                        new
                        {
                            Id = 17,
                            Area = 22000m,
                            Cidade = "Dourados",
                            Matricula = 7453,
                            Nome = "Fazenda Alto Alegre",
                            Proprietaria = "Alto Agro"
                        },
                        new
                        {
                            Id = 18,
                            Area = 4700m,
                            Cidade = "Uberlândia",
                            Matricula = 2987,
                            Nome = "Sítio Campo Belo",
                            Proprietaria = "Campo Forte"
                        },
                        new
                        {
                            Id = 19,
                            Area = 3500m,
                            Cidade = "Ribeirão Preto",
                            Matricula = 3654,
                            Nome = "Chácara Estrela do Sul",
                            Proprietaria = "Estrela Agro"
                        },
                        new
                        {
                            Id = 20,
                            Area = 27000m,
                            Cidade = "Goiânia",
                            Matricula = 8123,
                            Nome = "Fazenda Santa Helena",
                            Proprietaria = "Helena Agropecuária"
                        },
                        new
                        {
                            Id = 21,
                            Area = 5400m,
                            Cidade = "Chapecó",
                            Matricula = 2765,
                            Nome = "Sítio Água Clara",
                            Proprietaria = "Água Viva"
                        },
                        new
                        {
                            Id = 22,
                            Area = 4100m,
                            Cidade = "Poços de Caldas",
                            Matricula = 3498,
                            Nome = "Chácara Monte Verde",
                            Proprietaria = "Monte Verde Ltda"
                        },
                        new
                        {
                            Id = 23,
                            Area = 31000m,
                            Cidade = "Uberaba",
                            Matricula = 9231,
                            Nome = "Fazenda Ouro Branco",
                            Proprietaria = "Ouro Agro"
                        },
                        new
                        {
                            Id = 24,
                            Area = 4800m,
                            Cidade = "Joinville",
                            Matricula = 2574,
                            Nome = "Sítio Lago Azul",
                            Proprietaria = "Lago Azul Ltda"
                        },
                        new
                        {
                            Id = 25,
                            Area = 3300m,
                            Cidade = "Sorocaba",
                            Matricula = 3189,
                            Nome = "Chácara Boa Esperança",
                            Proprietaria = "Esperança Rural"
                        },
                        new
                        {
                            Id = 26,
                            Area = 29000m,
                            Cidade = "Palmas",
                            Matricula = 8675,
                            Nome = "Fazenda Santa Rita",
                            Proprietaria = "Santa Rita Agro"
                        },
                        new
                        {
                            Id = 27,
                            Area = 5600m,
                            Cidade = "Nova Friburgo",
                            Matricula = 2999,
                            Nome = "Sítio Encanto da Serra",
                            Proprietaria = "Encanto Verde"
                        },
                        new
                        {
                            Id = 28,
                            Area = 21000m,
                            Cidade = "Sinop",
                            Matricula = 9342,
                            Nome = "Fazenda Rio Dourado",
                            Proprietaria = "Rio Agro"
                        },
                        new
                        {
                            Id = 29,
                            Area = 4300m,
                            Cidade = "Itu",
                            Matricula = 2781,
                            Nome = "Sítio Bela Vista",
                            Proprietaria = "Bela Vista Rural"
                        },
                        new
                        {
                            Id = 30,
                            Area = 3200m,
                            Cidade = "Jundiaí",
                            Matricula = 3567,
                            Nome = "Chácara Recanto Feliz",
                            Proprietaria = "Recanto Ltda"
                        },
                        new
                        {
                            Id = 31,
                            Area = 26000m,
                            Cidade = "Rondonópolis",
                            Matricula = 8452,
                            Nome = "Fazenda Santa Clara",
                            Proprietaria = "Santa Clara Agro"
                        },
                        new
                        {
                            Id = 32,
                            Area = 5100m,
                            Cidade = "Passo Fundo",
                            Matricula = 2643,
                            Nome = "Sítio Vale Verde",
                            Proprietaria = "Vale Verde Ltda"
                        },
                        new
                        {
                            Id = 33,
                            Area = 3700m,
                            Cidade = "Campinas",
                            Matricula = 3894,
                            Nome = "Chácara Sol Nascente",
                            Proprietaria = "Sol Nascente Agro"
                        },
                        new
                        {
                            Id = 34,
                            Area = 28000m,
                            Cidade = "Três Lagoas",
                            Matricula = 9021,
                            Nome = "Fazenda Três Lagoas",
                            Proprietaria = "Lagoas Agro"
                        },
                        new
                        {
                            Id = 35,
                            Area = 4900m,
                            Cidade = "Domingos Martins",
                            Matricula = 2956,
                            Nome = "Sítio Pedra Azul",
                            Proprietaria = "Pedra Azul Ltda"
                        },
                        new
                        {
                            Id = 36,
                            Area = 3400m,
                            Cidade = "Atibaia",
                            Matricula = 3722,
                            Nome = "Chácara Vale Encantado",
                            Proprietaria = "Encanto Rural"
                        },
                        new
                        {
                            Id = 37,
                            Area = 30000m,
                            Cidade = "Barreiras",
                            Matricula = 9784,
                            Nome = "Fazenda Boa Esperança",
                            Proprietaria = "Boa Esperança Agro"
                        },
                        new
                        {
                            Id = 38,
                            Area = 4600m,
                            Cidade = "São José dos Pinhais",
                            Matricula = 2819,
                            Nome = "Sítio Água Verde",
                            Proprietaria = "Água Verde Ltda"
                        },
                        new
                        {
                            Id = 39,
                            Area = 3600m,
                            Cidade = "Anápolis",
                            Matricula = 3475,
                            Nome = "Chácara Serra Dourada",
                            Proprietaria = "Serra Dourada Agro"
                        },
                        new
                        {
                            Id = 40,
                            Area = 27000m,
                            Cidade = "Campo Grande",
                            Matricula = 8891,
                            Nome = "Fazenda Campo Grande",
                            Proprietaria = "Campo Grande Agro"
                        },
                        new
                        {
                            Id = 41,
                            Area = 5200m,
                            Cidade = "Lages",
                            Matricula = 2637,
                            Nome = "Sítio Vista Alegre",
                            Proprietaria = "Vista Alegre Rural"
                        },
                        new
                        {
                            Id = 42,
                            Area = 3100m,
                            Cidade = "Araraquara",
                            Matricula = 3588,
                            Nome = "Chácara Morada do Sol",
                            Proprietaria = "Morada Ltda"
                        },
                        new
                        {
                            Id = 43,
                            Area = 24000m,
                            Cidade = "Cuiabá",
                            Matricula = 8129,
                            Nome = "Fazenda Santa Tereza",
                            Proprietaria = "Santa Tereza Agro"
                        },
                        new
                        {
                            Id = 44,
                            Area = 4800m,
                            Cidade = "Holambra",
                            Matricula = 2991,
                            Nome = "Sítio Recanto das Flores",
                            Proprietaria = "Flores do Campo"
                        },
                        new
                        {
                            Id = 45,
                            Area = 3500m,
                            Cidade = "São Carlos",
                            Matricula = 3662,
                            Nome = "Chácara Jardim das Palmeiras",
                            Proprietaria = "Palmeiras Ltda"
                        },
                        new
                        {
                            Id = 46,
                            Area = 32000m,
                            Cidade = "Imperatriz",
                            Matricula = 9953,
                            Nome = "Fazenda Vale do Rio",
                            Proprietaria = "Vale do Rio Agro"
                        },
                        new
                        {
                            Id = 47,
                            Area = 5300m,
                            Cidade = "Petrópolis",
                            Matricula = 2714,
                            Nome = "Sítio Encosta Verde",
                            Proprietaria = "Encosta Ltda"
                        },
                        new
                        {
                            Id = 48,
                            Area = 23000m,
                            Cidade = "Londrina",
                            Matricula = 9027,
                            Nome = "Fazenda Boa Vista",
                            Proprietaria = "AgroSul"
                        },
                        new
                        {
                            Id = 49,
                            Area = 5000m,
                            Cidade = "Guarapuava",
                            Matricula = 2841,
                            Nome = "Sítio Bela Serra",
                            Proprietaria = "SerraAlta"
                        },
                        new
                        {
                            Id = 50,
                            Area = 3600m,
                            Cidade = "Ponta Grossa",
                            Matricula = 3312,
                            Nome = "Chácara Vale do Sol",
                            Proprietaria = "ValeSul"
                        },
                        new
                        {
                            Id = 51,
                            Area = 25500m,
                            Cidade = "Campo Grande",
                            Matricula = 5610,
                            Nome = "Fazenda Horizonte",
                            Proprietaria = "TerraNova"
                        },
                        new
                        {
                            Id = 52,
                            Area = 6200m,
                            Cidade = "Blumenau",
                            Matricula = 4268,
                            Nome = "Sítio Pedra Branca",
                            Proprietaria = "PedraSul"
                        },
                        new
                        {
                            Id = 53,
                            Area = 3000m,
                            Cidade = "Florianópolis",
                            Matricula = 3925,
                            Nome = "Chácara Primavera",
                            Proprietaria = "Primavera Ltda"
                        },
                        new
                        {
                            Id = 54,
                            Area = 21500m,
                            Cidade = "Dourados",
                            Matricula = 7489,
                            Nome = "Fazenda Alto Alegre",
                            Proprietaria = "Alto Agro"
                        },
                        new
                        {
                            Id = 55,
                            Area = 4700m,
                            Cidade = "Uberlândia",
                            Matricula = 2971,
                            Nome = "Sítio Campo Belo",
                            Proprietaria = "Campo Forte"
                        },
                        new
                        {
                            Id = 56,
                            Area = 3400m,
                            Cidade = "Ribeirão Preto",
                            Matricula = 3620,
                            Nome = "Chácara Estrela do Sul",
                            Proprietaria = "Estrela Agro"
                        },
                        new
                        {
                            Id = 57,
                            Area = 27500m,
                            Cidade = "Goiânia",
                            Matricula = 8188,
                            Nome = "Fazenda Santa Helena",
                            Proprietaria = "Helena Agropecuária"
                        },
                        new
                        {
                            Id = 58,
                            Area = 5500m,
                            Cidade = "Chapecó",
                            Matricula = 2793,
                            Nome = "Sítio Água Clara",
                            Proprietaria = "Água Viva"
                        },
                        new
                        {
                            Id = 59,
                            Area = 4200m,
                            Cidade = "Poços de Caldas",
                            Matricula = 3521,
                            Nome = "Chácara Monte Verde",
                            Proprietaria = "Monte Verde Ltda"
                        },
                        new
                        {
                            Id = 60,
                            Area = 30500m,
                            Cidade = "Uberaba",
                            Matricula = 9277,
                            Nome = "Fazenda Ouro Branco",
                            Proprietaria = "Ouro Agro"
                        },
                        new
                        {
                            Id = 61,
                            Area = 4900m,
                            Cidade = "Joinville",
                            Matricula = 2598,
                            Nome = "Sítio Lago Azul",
                            Proprietaria = "Lago Azul Ltda"
                        },
                        new
                        {
                            Id = 62,
                            Area = 3200m,
                            Cidade = "Sorocaba",
                            Matricula = 3155,
                            Nome = "Chácara Boa Esperança",
                            Proprietaria = "Esperança Rural"
                        },
                        new
                        {
                            Id = 63,
                            Area = 29500m,
                            Cidade = "Palmas",
                            Matricula = 8721,
                            Nome = "Fazenda Santa Rita",
                            Proprietaria = "Santa Rita Agro"
                        },
                        new
                        {
                            Id = 64,
                            Area = 5700m,
                            Cidade = "Nova Friburgo",
                            Matricula = 3012,
                            Nome = "Sítio Encanto da Serra",
                            Proprietaria = "Encanto Verde"
                        },
                        new
                        {
                            Id = 65,
                            Area = 3300m,
                            Cidade = "Jundiaí",
                            Matricula = 3599,
                            Nome = "Chácara Recanto Feliz",
                            Proprietaria = "Recanto Ltda"
                        },
                        new
                        {
                            Id = 66,
                            Area = 26800m,
                            Cidade = "Campo Grande",
                            Matricula = 8842,
                            Nome = "Fazenda Campo Grande",
                            Proprietaria = "Campo Grande Agro"
                        },
                        new
                        {
                            Id = 67,
                            Area = 5100m,
                            Cidade = "Lages",
                            Matricula = 2610,
                            Nome = "Sítio Vista Alegre",
                            Proprietaria = "Vista Alegre Rural"
                        },
                        new
                        {
                            Id = 68,
                            Area = 22500m,
                            Cidade = "Sinop",
                            Matricula = 9365,
                            Nome = "Fazenda Rio Dourado",
                            Proprietaria = "Rio Agro"
                        },
                        new
                        {
                            Id = 69,
                            Area = 4400m,
                            Cidade = "Itu",
                            Matricula = 2798,
                            Nome = "Sítio Bela Vista",
                            Proprietaria = "Bela Vista Rural"
                        },
                        new
                        {
                            Id = 70,
                            Area = 3800m,
                            Cidade = "Campinas",
                            Matricula = 3912,
                            Nome = "Chácara Sol Nascente",
                            Proprietaria = "Sol Nascente Agro"
                        },
                        new
                        {
                            Id = 71,
                            Area = 28500m,
                            Cidade = "Três Lagoas",
                            Matricula = 9054,
                            Nome = "Fazenda Três Lagoas",
                            Proprietaria = "Lagoas Agro"
                        },
                        new
                        {
                            Id = 72,
                            Area = 5000m,
                            Cidade = "Domingos Martins",
                            Matricula = 2983,
                            Nome = "Sítio Pedra Azul",
                            Proprietaria = "Pedra Azul Ltda"
                        },
                        new
                        {
                            Id = 73,
                            Area = 3500m,
                            Cidade = "Atibaia",
                            Matricula = 3740,
                            Nome = "Chácara Vale Encantado",
                            Proprietaria = "Encanto Rural"
                        },
                        new
                        {
                            Id = 74,
                            Area = 30500m,
                            Cidade = "Barreiras",
                            Matricula = 9802,
                            Nome = "Fazenda Boa Esperança",
                            Proprietaria = "Boa Esperança Agro"
                        },
                        new
                        {
                            Id = 75,
                            Area = 4700m,
                            Cidade = "São José dos Pinhais",
                            Matricula = 2835,
                            Nome = "Sítio Água Verde",
                            Proprietaria = "Água Verde Ltda"
                        },
                        new
                        {
                            Id = 76,
                            Area = 3650m,
                            Cidade = "Anápolis",
                            Matricula = 3492,
                            Nome = "Chácara Serra Dourada",
                            Proprietaria = "Serra Dourada Agro"
                        },
                        new
                        {
                            Id = 77,
                            Area = 26000m,
                            Cidade = "Rondonópolis",
                            Matricula = 8477,
                            Nome = "Fazenda Santa Clara",
                            Proprietaria = "Santa Clara Agro"
                        },
                        new
                        {
                            Id = 78,
                            Area = 5200m,
                            Cidade = "Passo Fundo",
                            Matricula = 2661,
                            Nome = "Sítio Vale Verde",
                            Proprietaria = "Vale Verde Ltda"
                        },
                        new
                        {
                            Id = 79,
                            Area = 3200m,
                            Cidade = "Araraquara",
                            Matricula = 3604,
                            Nome = "Chácara Morada do Sol",
                            Proprietaria = "Morada Ltda"
                        },
                        new
                        {
                            Id = 80,
                            Area = 24500m,
                            Cidade = "Cuiabá",
                            Matricula = 8150,
                            Nome = "Fazenda Santa Tereza",
                            Proprietaria = "Santa Tereza Agro"
                        },
                        new
                        {
                            Id = 81,
                            Area = 4900m,
                            Cidade = "Holambra",
                            Matricula = 3007,
                            Nome = "Sítio Recanto das Flores",
                            Proprietaria = "Flores do Campo"
                        },
                        new
                        {
                            Id = 82,
                            Area = 3600m,
                            Cidade = "São Carlos",
                            Matricula = 3688,
                            Nome = "Chácara Jardim das Palmeiras",
                            Proprietaria = "Palmeiras Ltda"
                        },
                        new
                        {
                            Id = 83,
                            Area = 32500m,
                            Cidade = "Imperatriz",
                            Matricula = 9981,
                            Nome = "Fazenda Vale do Rio",
                            Proprietaria = "Vale do Rio Agro"
                        },
                        new
                        {
                            Id = 84,
                            Area = 5400m,
                            Cidade = "Petrópolis",
                            Matricula = 2730,
                            Nome = "Sítio Encosta Verde",
                            Proprietaria = "Encosta Ltda"
                        },
                        new
                        {
                            Id = 85,
                            Area = 3300m,
                            Cidade = "Maringá",
                            Matricula = 3615,
                            Nome = "Chácara Recanto Verde",
                            Proprietaria = "VerdeVale"
                        },
                        new
                        {
                            Id = 86,
                            Area = 18200m,
                            Cidade = "Cascavel",
                            Matricula = 6754,
                            Nome = "Fazenda Três Rios",
                            Proprietaria = "AgroRios"
                        },
                        new
                        {
                            Id = 87,
                            Area = 5600m,
                            Cidade = "Chapecó",
                            Matricula = 3033,
                            Nome = "Sítio Água Clara",
                            Proprietaria = "Água Viva"
                        },
                        new
                        {
                            Id = 88,
                            Area = 26000m,
                            Cidade = "Campo Grande",
                            Matricula = 5638,
                            Nome = "Fazenda Horizonte",
                            Proprietaria = "TerraNova"
                        },
                        new
                        {
                            Id = 89,
                            Area = 6300m,
                            Cidade = "Blumenau",
                            Matricula = 4285,
                            Nome = "Sítio Pedra Branca",
                            Proprietaria = "PedraSul"
                        },
                        new
                        {
                            Id = 90,
                            Area = 3100m,
                            Cidade = "Florianópolis",
                            Matricula = 3950,
                            Nome = "Chácara Primavera",
                            Proprietaria = "Primavera Ltda"
                        },
                        new
                        {
                            Id = 91,
                            Area = 22000m,
                            Cidade = "Dourados",
                            Matricula = 7521,
                            Nome = "Fazenda Alto Alegre",
                            Proprietaria = "Alto Agro"
                        },
                        new
                        {
                            Id = 92,
                            Area = 4800m,
                            Cidade = "Uberlândia",
                            Matricula = 2995,
                            Nome = "Sítio Campo Belo",
                            Proprietaria = "Campo Forte"
                        },
                        new
                        {
                            Id = 93,
                            Area = 3500m,
                            Cidade = "Ribeirão Preto",
                            Matricula = 3641,
                            Nome = "Chácara Estrela do Sul",
                            Proprietaria = "Estrela Agro"
                        },
                        new
                        {
                            Id = 94,
                            Area = 28000m,
                            Cidade = "Goiânia",
                            Matricula = 8205,
                            Nome = "Fazenda Santa Helena",
                            Proprietaria = "Helena Agropecuária"
                        },
                        new
                        {
                            Id = 95,
                            Area = 5700m,
                            Cidade = "Chapecó",
                            Matricula = 3050,
                            Nome = "Sítio Água Clara",
                            Proprietaria = "Água Viva"
                        },
                        new
                        {
                            Id = 96,
                            Area = 4300m,
                            Cidade = "Poços de Caldas",
                            Matricula = 3544,
                            Nome = "Chácara Monte Verde",
                            Proprietaria = "Monte Verde Ltda"
                        },
                        new
                        {
                            Id = 97,
                            Area = 31000m,
                            Cidade = "Uberaba",
                            Matricula = 9302,
                            Nome = "Fazenda Ouro Branco",
                            Proprietaria = "Ouro Agro"
                        },
                        new
                        {
                            Id = 98,
                            Area = 5000m,
                            Cidade = "Joinville",
                            Matricula = 2620,
                            Nome = "Sítio Lago Azul",
                            Proprietaria = "Lago Azul Ltda"
                        },
                        new
                        {
                            Id = 99,
                            Area = 3400m,
                            Cidade = "Sorocaba",
                            Matricula = 3180,
                            Nome = "Chácara Boa Esperança",
                            Proprietaria = "Esperança Rural"
                        },
                        new
                        {
                            Id = 100,
                            Area = 30000m,
                            Cidade = "Palmas",
                            Matricula = 8750,
                            Nome = "Fazenda Santa Rita",
                            Proprietaria = "Santa Rita Agro"
                        },
                        new
                        {
                            Id = 101,
                            Area = 5800m,
                            Cidade = "Nova Friburgo",
                            Matricula = 3072,
                            Nome = "Sítio Encanto da Serra",
                            Proprietaria = "Encanto Verde"
                        },
                        new
                        {
                            Id = 102,
                            Area = 3500m,
                            Cidade = "Jundiaí",
                            Matricula = 3628,
                            Nome = "Chácara Recanto Feliz",
                            Proprietaria = "Recanto Ltda"
                        },
                        new
                        {
                            Id = 103,
                            Area = 27500m,
                            Cidade = "Campo Grande",
                            Matricula = 8870,
                            Nome = "Fazenda Campo Grande",
                            Proprietaria = "Campo Grande Agro"
                        },
                        new
                        {
                            Id = 104,
                            Area = 5200m,
                            Cidade = "Lages",
                            Matricula = 2630,
                            Nome = "Sítio Vista Alegre",
                            Proprietaria = "Vista Alegre Rural"
                        },
                        new
                        {
                            Id = 105,
                            Area = 3300m,
                            Cidade = "Araraquara",
                            Matricula = 3639,
                            Nome = "Chácara Morada do Sol",
                            Proprietaria = "Morada Ltda"
                        },
                        new
                        {
                            Id = 106,
                            Area = 25000m,
                            Cidade = "Cuiabá",
                            Matricula = 8182,
                            Nome = "Fazenda Santa Tereza",
                            Proprietaria = "Santa Tereza Agro"
                        },
                        new
                        {
                            Id = 107,
                            Area = 5000m,
                            Cidade = "Holambra",
                            Matricula = 3095,
                            Nome = "Sítio Recanto das Flores",
                            Proprietaria = "Flores do Campo"
                        },
                        new
                        {
                            Id = 108,
                            Area = 24000m,
                            Cidade = "Londrina",
                            Matricula = 9842,
                            Nome = "Fazenda Boa Vista",
                            Proprietaria = "AgroSul"
                        },
                        new
                        {
                            Id = 109,
                            Area = 5100m,
                            Cidade = "Guarapuava",
                            Matricula = 2888,
                            Nome = "Sítio Bela Serra",
                            Proprietaria = "SerraAlta"
                        },
                        new
                        {
                            Id = 110,
                            Area = 3700m,
                            Cidade = "Ponta Grossa",
                            Matricula = 3360,
                            Nome = "Chácara Vale do Sol",
                            Proprietaria = "ValeSul"
                        },
                        new
                        {
                            Id = 111,
                            Area = 26500m,
                            Cidade = "Campo Grande",
                            Matricula = 5689,
                            Nome = "Fazenda Horizonte",
                            Proprietaria = "TerraNova"
                        },
                        new
                        {
                            Id = 112,
                            Area = 6400m,
                            Cidade = "Blumenau",
                            Matricula = 4310,
                            Nome = "Sítio Pedra Branca",
                            Proprietaria = "PedraSul"
                        },
                        new
                        {
                            Id = 113,
                            Area = 3200m,
                            Cidade = "Florianópolis",
                            Matricula = 3982,
                            Nome = "Chácara Primavera",
                            Proprietaria = "Primavera Ltda"
                        },
                        new
                        {
                            Id = 114,
                            Area = 22500m,
                            Cidade = "Dourados",
                            Matricula = 7560,
                            Nome = "Fazenda Alto Alegre",
                            Proprietaria = "Alto Agro"
                        },
                        new
                        {
                            Id = 115,
                            Area = 4900m,
                            Cidade = "Uberlândia",
                            Matricula = 3011,
                            Nome = "Sítio Campo Belo",
                            Proprietaria = "Campo Forte"
                        },
                        new
                        {
                            Id = 116,
                            Area = 3600m,
                            Cidade = "Ribeirão Preto",
                            Matricula = 3678,
                            Nome = "Chácara Estrela do Sul",
                            Proprietaria = "Estrela Agro"
                        },
                        new
                        {
                            Id = 117,
                            Area = 28500m,
                            Cidade = "Goiânia",
                            Matricula = 8239,
                            Nome = "Fazenda Santa Helena",
                            Proprietaria = "Helena Agropecuária"
                        },
                        new
                        {
                            Id = 118,
                            Area = 5800m,
                            Cidade = "Chapecó",
                            Matricula = 3108,
                            Nome = "Sítio Água Clara",
                            Proprietaria = "Água Viva"
                        },
                        new
                        {
                            Id = 119,
                            Area = 4400m,
                            Cidade = "Poços de Caldas",
                            Matricula = 3570,
                            Nome = "Chácara Monte Verde",
                            Proprietaria = "Monte Verde Ltda"
                        },
                        new
                        {
                            Id = 120,
                            Area = 31500m,
                            Cidade = "Uberaba",
                            Matricula = 9350,
                            Nome = "Fazenda Ouro Branco",
                            Proprietaria = "Ouro Agro"
                        },
                        new
                        {
                            Id = 121,
                            Area = 5100m,
                            Cidade = "Joinville",
                            Matricula = 2655,
                            Nome = "Sítio Lago Azul",
                            Proprietaria = "Lago Azul Ltda"
                        },
                        new
                        {
                            Id = 122,
                            Area = 3500m,
                            Cidade = "Sorocaba",
                            Matricula = 3202,
                            Nome = "Chácara Boa Esperança",
                            Proprietaria = "Esperança Rural"
                        },
                        new
                        {
                            Id = 123,
                            Area = 30500m,
                            Cidade = "Palmas",
                            Matricula = 8799,
                            Nome = "Fazenda Santa Rita",
                            Proprietaria = "Santa Rita Agro"
                        },
                        new
                        {
                            Id = 124,
                            Area = 5900m,
                            Cidade = "Nova Friburgo",
                            Matricula = 3125,
                            Nome = "Sítio Encanto da Serra",
                            Proprietaria = "Encanto Verde"
                        },
                        new
                        {
                            Id = 125,
                            Area = 3600m,
                            Cidade = "Jundiaí",
                            Matricula = 3666,
                            Nome = "Chácara Recanto Feliz",
                            Proprietaria = "Recanto Ltda"
                        },
                        new
                        {
                            Id = 126,
                            Area = 28000m,
                            Cidade = "Campo Grande",
                            Matricula = 8915,
                            Nome = "Fazenda Campo Grande",
                            Proprietaria = "Campo Grande Agro"
                        },
                        new
                        {
                            Id = 127,
                            Area = 5300m,
                            Cidade = "Lages",
                            Matricula = 2668,
                            Nome = "Sítio Vista Alegre",
                            Proprietaria = "Vista Alegre Rural"
                        },
                        new
                        {
                            Id = 128,
                            Area = 3400m,
                            Cidade = "Araraquara",
                            Matricula = 3695,
                            Nome = "Chácara Morada do Sol",
                            Proprietaria = "Morada Ltda"
                        },
                        new
                        {
                            Id = 129,
                            Area = 25500m,
                            Cidade = "Cuiabá",
                            Matricula = 8221,
                            Nome = "Fazenda Santa Tereza",
                            Proprietaria = "Santa Tereza Agro"
                        },
                        new
                        {
                            Id = 130,
                            Area = 5100m,
                            Cidade = "Holambra",
                            Matricula = 3133,
                            Nome = "Sítio Recanto das Flores",
                            Proprietaria = "Flores do Campo"
                        },
                        new
                        {
                            Id = 131,
                            Area = 3700m,
                            Cidade = "São Carlos",
                            Matricula = 3710,
                            Nome = "Chácara Jardim das Palmeiras",
                            Proprietaria = "Palmeiras Ltda"
                        },
                        new
                        {
                            Id = 132,
                            Area = 33000m,
                            Cidade = "Imperatriz",
                            Matricula = 10012,
                            Nome = "Fazenda Vale do Rio",
                            Proprietaria = "Vale do Rio Agro"
                        },
                        new
                        {
                            Id = 133,
                            Area = 5500m,
                            Cidade = "Petrópolis",
                            Matricula = 2755,
                            Nome = "Sítio Encosta Verde",
                            Proprietaria = "Encosta Ltda"
                        },
                        new
                        {
                            Id = 134,
                            Area = 3400m,
                            Cidade = "Maringá",
                            Matricula = 3640,
                            Nome = "Chácara Recanto Verde",
                            Proprietaria = "VerdeVale"
                        },
                        new
                        {
                            Id = 135,
                            Area = 18500m,
                            Cidade = "Cascavel",
                            Matricula = 6788,
                            Nome = "Fazenda Três Rios",
                            Proprietaria = "AgroRios"
                        },
                        new
                        {
                            Id = 136,
                            Area = 6000m,
                            Cidade = "Chapecó",
                            Matricula = 3159,
                            Nome = "Sítio Água Clara",
                            Proprietaria = "Água Viva"
                        },
                        new
                        {
                            Id = 137,
                            Area = 3900m,
                            Cidade = "Campinas",
                            Matricula = 3935,
                            Nome = "Chácara Sol Nascente",
                            Proprietaria = "Sol Nascente Agro"
                        },
                        new
                        {
                            Id = 138,
                            Area = 29000m,
                            Cidade = "Três Lagoas",
                            Matricula = 9089,
                            Nome = "Fazenda Três Lagoas",
                            Proprietaria = "Lagoas Agro"
                        },
                        new
                        {
                            Id = 139,
                            Area = 5200m,
                            Cidade = "Domingos Martins",
                            Matricula = 3008,
                            Nome = "Sítio Pedra Azul",
                            Proprietaria = "Pedra Azul Ltda"
                        },
                        new
                        {
                            Id = 140,
                            Area = 3600m,
                            Cidade = "Atibaia",
                            Matricula = 3762,
                            Nome = "Chácara Vale Encantado",
                            Proprietaria = "Encanto Rural"
                        },
                        new
                        {
                            Id = 141,
                            Area = 31000m,
                            Cidade = "Barreiras",
                            Matricula = 9833,
                            Nome = "Fazenda Boa Esperança",
                            Proprietaria = "Boa Esperança Agro"
                        },
                        new
                        {
                            Id = 142,
                            Area = 4800m,
                            Cidade = "São José dos Pinhais",
                            Matricula = 2860,
                            Nome = "Sítio Água Verde",
                            Proprietaria = "Água Verde Ltda"
                        },
                        new
                        {
                            Id = 143,
                            Area = 3700m,
                            Cidade = "Anápolis",
                            Matricula = 3515,
                            Nome = "Chácara Serra Dourada",
                            Proprietaria = "Serra Dourada Agro"
                        },
                        new
                        {
                            Id = 144,
                            Area = 26500m,
                            Cidade = "Rondonópolis",
                            Matricula = 8505,
                            Nome = "Fazenda Santa Clara",
                            Proprietaria = "Santa Clara Agro"
                        },
                        new
                        {
                            Id = 145,
                            Area = 5300m,
                            Cidade = "Passo Fundo",
                            Matricula = 2689,
                            Nome = "Sítio Vale Verde",
                            Proprietaria = "Vale Verde Ltda"
                        },
                        new
                        {
                            Id = 146,
                            Area = 3700m,
                            Cidade = "Jundiaí",
                            Matricula = 3685,
                            Nome = "Chácara Recanto Feliz",
                            Proprietaria = "Recanto Ltda"
                        },
                        new
                        {
                            Id = 147,
                            Area = 28500m,
                            Cidade = "Campo Grande",
                            Matricula = 8950,
                            Nome = "Fazenda Campo Grande",
                            Proprietaria = "Campo Grande Agro"
                        },
                        new
                        {
                            Id = 148,
                            Area = 5400m,
                            Cidade = "Lages",
                            Matricula = 2705,
                            Nome = "Sítio Vista Alegre",
                            Proprietaria = "Vista Alegre Rural"
                        },
                        new
                        {
                            Id = 149,
                            Area = 3500m,
                            Cidade = "Araraquara",
                            Matricula = 3728,
                            Nome = "Chácara Morada do Sol",
                            Proprietaria = "Morada Ltda"
                        },
                        new
                        {
                            Id = 150,
                            Area = 26000m,
                            Cidade = "Cuiabá",
                            Matricula = 8254,
                            Nome = "Fazenda Santa Tereza",
                            Proprietaria = "Santa Tereza Agro"
                        },
                        new
                        {
                            Id = 151,
                            Area = 5200m,
                            Cidade = "Holambra",
                            Matricula = 3167,
                            Nome = "Sítio Recanto das Flores",
                            Proprietaria = "Flores do Campo"
                        },
                        new
                        {
                            Id = 152,
                            Area = 3800m,
                            Cidade = "São Carlos",
                            Matricula = 3739,
                            Nome = "Chácara Jardim das Palmeiras",
                            Proprietaria = "Palmeiras Ltda"
                        },
                        new
                        {
                            Id = 153,
                            Area = 33500m,
                            Cidade = "Imperatriz",
                            Matricula = 10045,
                            Nome = "Fazenda Vale do Rio",
                            Proprietaria = "Vale do Rio Agro"
                        },
                        new
                        {
                            Id = 154,
                            Area = 5600m,
                            Cidade = "Petrópolis",
                            Matricula = 2780,
                            Nome = "Sítio Encosta Verde",
                            Proprietaria = "Encosta Ltda"
                        },
                        new
                        {
                            Id = 155,
                            Area = 3500m,
                            Cidade = "Maringá",
                            Matricula = 3661,
                            Nome = "Chácara Recanto Verde",
                            Proprietaria = "VerdeVale"
                        },
                        new
                        {
                            Id = 156,
                            Area = 19000m,
                            Cidade = "Cascavel",
                            Matricula = 6812,
                            Nome = "Fazenda Três Rios",
                            Proprietaria = "AgroRios"
                        },
                        new
                        {
                            Id = 157,
                            Area = 6100m,
                            Cidade = "Chapecó",
                            Matricula = 3184,
                            Nome = "Sítio Água Clara",
                            Proprietaria = "Água Viva"
                        },
                        new
                        {
                            Id = 158,
                            Area = 4000m,
                            Cidade = "Campinas",
                            Matricula = 3960,
                            Nome = "Chácara Sol Nascente",
                            Proprietaria = "Sol Nascente Agro"
                        },
                        new
                        {
                            Id = 159,
                            Area = 29500m,
                            Cidade = "Três Lagoas",
                            Matricula = 9120,
                            Nome = "Fazenda Três Lagoas",
                            Proprietaria = "Lagoas Agro"
                        },
                        new
                        {
                            Id = 160,
                            Area = 5300m,
                            Cidade = "Domingos Martins",
                            Matricula = 3035,
                            Nome = "Sítio Pedra Azul",
                            Proprietaria = "Pedra Azul Ltda"
                        },
                        new
                        {
                            Id = 161,
                            Area = 3700m,
                            Cidade = "Atibaia",
                            Matricula = 3788,
                            Nome = "Chácara Vale Encantado",
                            Proprietaria = "Encanto Rural"
                        },
                        new
                        {
                            Id = 162,
                            Area = 31500m,
                            Cidade = "Barreiras",
                            Matricula = 9860,
                            Nome = "Fazenda Boa Esperança",
                            Proprietaria = "Boa Esperança Agro"
                        },
                        new
                        {
                            Id = 163,
                            Area = 4900m,
                            Cidade = "São José dos Pinhais",
                            Matricula = 2884,
                            Nome = "Sítio Água Verde",
                            Proprietaria = "Água Verde Ltda"
                        },
                        new
                        {
                            Id = 164,
                            Area = 3800m,
                            Cidade = "Anápolis",
                            Matricula = 3540,
                            Nome = "Chácara Serra Dourada",
                            Proprietaria = "Serra Dourada Agro"
                        },
                        new
                        {
                            Id = 165,
                            Area = 27000m,
                            Cidade = "Rondonópolis",
                            Matricula = 8533,
                            Nome = "Fazenda Santa Clara",
                            Proprietaria = "Santa Clara Agro"
                        },
                        new
                        {
                            Id = 166,
                            Area = 5400m,
                            Cidade = "Passo Fundo",
                            Matricula = 2715,
                            Nome = "Sítio Vale Verde",
                            Proprietaria = "Vale Verde Ltda"
                        },
                        new
                        {
                            Id = 167,
                            Area = 3800m,
                            Cidade = "Jundiaí",
                            Matricula = 3709,
                            Nome = "Chácara Recanto Feliz",
                            Proprietaria = "Recanto Ltda"
                        },
                        new
                        {
                            Id = 168,
                            Area = 29000m,
                            Cidade = "Campo Grande",
                            Matricula = 8982,
                            Nome = "Fazenda Campo Grande",
                            Proprietaria = "Campo Grande Agro"
                        },
                        new
                        {
                            Id = 169,
                            Area = 5500m,
                            Cidade = "Lages",
                            Matricula = 2738,
                            Nome = "Sítio Vista Alegre",
                            Proprietaria = "Vista Alegre Rural"
                        },
                        new
                        {
                            Id = 170,
                            Area = 3600m,
                            Cidade = "Araraquara",
                            Matricula = 3756,
                            Nome = "Chácara Morada do Sol",
                            Proprietaria = "Morada Ltda"
                        },
                        new
                        {
                            Id = 171,
                            Area = 26500m,
                            Cidade = "Cuiabá",
                            Matricula = 8289,
                            Nome = "Fazenda Santa Tereza",
                            Proprietaria = "Santa Tereza Agro"
                        },
                        new
                        {
                            Id = 172,
                            Area = 5300m,
                            Cidade = "Holambra",
                            Matricula = 3199,
                            Nome = "Sítio Recanto das Flores",
                            Proprietaria = "Flores do Campo"
                        },
                        new
                        {
                            Id = 173,
                            Area = 3900m,
                            Cidade = "São Carlos",
                            Matricula = 3768,
                            Nome = "Chácara Jardim das Palmeiras",
                            Proprietaria = "Palmeiras Ltda"
                        },
                        new
                        {
                            Id = 174,
                            Area = 34000m,
                            Cidade = "Imperatriz",
                            Matricula = 10078,
                            Nome = "Fazenda Vale do Rio",
                            Proprietaria = "Vale do Rio Agro"
                        },
                        new
                        {
                            Id = 175,
                            Area = 5700m,
                            Cidade = "Petrópolis",
                            Matricula = 2804,
                            Nome = "Sítio Encosta Verde",
                            Proprietaria = "Encosta Ltda"
                        },
                        new
                        {
                            Id = 176,
                            Area = 3600m,
                            Cidade = "Maringá",
                            Matricula = 3684,
                            Nome = "Chácara Recanto Verde",
                            Proprietaria = "VerdeVale"
                        },
                        new
                        {
                            Id = 177,
                            Area = 19500m,
                            Cidade = "Cascavel",
                            Matricula = 6845,
                            Nome = "Fazenda Três Rios",
                            Proprietaria = "AgroRios"
                        },
                        new
                        {
                            Id = 178,
                            Area = 6200m,
                            Cidade = "Chapecó",
                            Matricula = 3210,
                            Nome = "Sítio Água Clara",
                            Proprietaria = "Água Viva"
                        },
                        new
                        {
                            Id = 179,
                            Area = 4100m,
                            Cidade = "Campinas",
                            Matricula = 3987,
                            Nome = "Chácara Sol Nascente",
                            Proprietaria = "Sol Nascente Agro"
                        },
                        new
                        {
                            Id = 180,
                            Area = 30000m,
                            Cidade = "Três Lagoas",
                            Matricula = 9156,
                            Nome = "Fazenda Três Lagoas",
                            Proprietaria = "Lagoas Agro"
                        },
                        new
                        {
                            Id = 181,
                            Area = 5400m,
                            Cidade = "Domingos Martins",
                            Matricula = 3062,
                            Nome = "Sítio Pedra Azul",
                            Proprietaria = "Pedra Azul Ltda"
                        },
                        new
                        {
                            Id = 182,
                            Area = 3800m,
                            Cidade = "Atibaia",
                            Matricula = 3815,
                            Nome = "Chácara Vale Encantado",
                            Proprietaria = "Encanto Rural"
                        },
                        new
                        {
                            Id = 183,
                            Area = 32000m,
                            Cidade = "Barreiras",
                            Matricula = 9894,
                            Nome = "Fazenda Boa Esperança",
                            Proprietaria = "Boa Esperança Agro"
                        },
                        new
                        {
                            Id = 184,
                            Area = 5000m,
                            Cidade = "São José dos Pinhais",
                            Matricula = 2907,
                            Nome = "Sítio Água Verde",
                            Proprietaria = "Água Verde Ltda"
                        },
                        new
                        {
                            Id = 185,
                            Area = 3900m,
                            Cidade = "Anápolis",
                            Matricula = 3566,
                            Nome = "Chácara Serra Dourada",
                            Proprietaria = "Serra Dourada Agro"
                        },
                        new
                        {
                            Id = 186,
                            Area = 27500m,
                            Cidade = "Rondonópolis",
                            Matricula = 8570,
                            Nome = "Fazenda Santa Clara",
                            Proprietaria = "Santa Clara Agro"
                        },
                        new
                        {
                            Id = 187,
                            Area = 5500m,
                            Cidade = "Passo Fundo",
                            Matricula = 2742,
                            Nome = "Sítio Vale Verde",
                            Proprietaria = "Vale Verde Ltda"
                        },
                        new
                        {
                            Id = 188,
                            Area = 3900m,
                            Cidade = "Jundiaí",
                            Matricula = 3735,
                            Nome = "Chácara Recanto Feliz",
                            Proprietaria = "Recanto Ltda"
                        },
                        new
                        {
                            Id = 189,
                            Area = 29500m,
                            Cidade = "Campo Grande",
                            Matricula = 9010,
                            Nome = "Fazenda Campo Grande",
                            Proprietaria = "Campo Grande Agro"
                        },
                        new
                        {
                            Id = 190,
                            Area = 5600m,
                            Cidade = "Lages",
                            Matricula = 2766,
                            Nome = "Sítio Vista Alegre",
                            Proprietaria = "Vista Alegre Rural"
                        },
                        new
                        {
                            Id = 191,
                            Area = 3700m,
                            Cidade = "Araraquara",
                            Matricula = 3780,
                            Nome = "Chácara Morada do Sol",
                            Proprietaria = "Morada Ltda"
                        },
                        new
                        {
                            Id = 192,
                            Area = 27000m,
                            Cidade = "Cuiabá",
                            Matricula = 8320,
                            Nome = "Fazenda Santa Tereza",
                            Proprietaria = "Santa Tereza Agro"
                        },
                        new
                        {
                            Id = 193,
                            Area = 5400m,
                            Cidade = "Holambra",
                            Matricula = 3228,
                            Nome = "Sítio Recanto das Flores",
                            Proprietaria = "Flores do Campo"
                        },
                        new
                        {
                            Id = 194,
                            Area = 4000m,
                            Cidade = "São Carlos",
                            Matricula = 3799,
                            Nome = "Chácara Jardim das Palmeiras",
                            Proprietaria = "Palmeiras Ltda"
                        },
                        new
                        {
                            Id = 195,
                            Area = 34500m,
                            Cidade = "Imperatriz",
                            Matricula = 10105,
                            Nome = "Fazenda Vale do Rio",
                            Proprietaria = "Vale do Rio Agro"
                        },
                        new
                        {
                            Id = 196,
                            Area = 5800m,
                            Cidade = "Petrópolis",
                            Matricula = 2831,
                            Nome = "Sítio Encosta Verde",
                            Proprietaria = "Encosta Ltda"
                        },
                        new
                        {
                            Id = 197,
                            Area = 3700m,
                            Cidade = "Maringá",
                            Matricula = 3702,
                            Nome = "Chácara Recanto Verde",
                            Proprietaria = "VerdeVale"
                        },
                        new
                        {
                            Id = 198,
                            Area = 20000m,
                            Cidade = "Cascavel",
                            Matricula = 6879,
                            Nome = "Fazenda Três Rios",
                            Proprietaria = "AgroRios"
                        },
                        new
                        {
                            Id = 199,
                            Area = 6300m,
                            Cidade = "Chapecó",
                            Matricula = 3244,
                            Nome = "Sítio Água Clara",
                            Proprietaria = "Água Viva"
                        },
                        new
                        {
                            Id = 200,
                            Area = 4200m,
                            Cidade = "Campinas",
                            Matricula = 4012,
                            Nome = "Chácara Sol Nascente",
                            Proprietaria = "Sol Nascente Agro"
                        },
                        new
                        {
                            Id = 201,
                            Area = 30500m,
                            Cidade = "Três Lagoas",
                            Matricula = 9188,
                            Nome = "Fazenda Três Lagoas",
                            Proprietaria = "Lagoas Agro"
                        },
                        new
                        {
                            Id = 202,
                            Area = 5500m,
                            Cidade = "Domingos Martins",
                            Matricula = 3089,
                            Nome = "Sítio Pedra Azul",
                            Proprietaria = "Pedra Azul Ltda"
                        },
                        new
                        {
                            Id = 203,
                            Area = 3900m,
                            Cidade = "Atibaia",
                            Matricula = 3840,
                            Nome = "Chácara Vale Encantado",
                            Proprietaria = "Encanto Rural"
                        },
                        new
                        {
                            Id = 204,
                            Area = 32500m,
                            Cidade = "Barreiras",
                            Matricula = 9925,
                            Nome = "Fazenda Boa Esperança",
                            Proprietaria = "Boa Esperança Agro"
                        },
                        new
                        {
                            Id = 205,
                            Area = 5100m,
                            Cidade = "São José dos Pinhais",
                            Matricula = 2930,
                            Nome = "Sítio Água Verde",
                            Proprietaria = "Água Verde Ltda"
                        },
                        new
                        {
                            Id = 206,
                            Area = 4000m,
                            Cidade = "Anápolis",
                            Matricula = 3592,
                            Nome = "Chácara Serra Dourada",
                            Proprietaria = "Serra Dourada Agro"
                        },
                        new
                        {
                            Id = 207,
                            Area = 28000m,
                            Cidade = "Rondonópolis",
                            Matricula = 8602,
                            Nome = "Fazenda Santa Clara",
                            Proprietaria = "Santa Clara Agro"
                        });
                });

            modelBuilder.Entity("Sistema.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistema.Modelos.Foto", b =>
                {
                    b.HasOne("Sistema.Modelos.Relatorios", "Relatorios")
                        .WithMany("Fotos")
                        .HasForeignKey("RelatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("Sistema.Modelos.Relatorios", b =>
                {
                    b.HasOne("Sistema.Modelos.Terrenos", "Terreno")
                        .WithMany("Relatorios")
                        .HasForeignKey("TerrenoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terreno");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema.Modelos.Relatorios", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Sistema.Modelos.Terrenos", b =>
                {
                    b.Navigation("Relatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
