using Microsoft.EntityFrameworkCore;
using Sistema.Modelos;

namespace Sistema.Repository

{
    public class MeuDbContext : DbContext
    {
        public MeuDbContext(DbContextOptions<MeuDbContext> options) : base(options) { }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Terrenos> Terrenos { get; set; }
        public DbSet<Relatorios> Relatorios { get; set; }
        public DbSet<Foto> Foto { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Foto>()
            .HasOne(f => f.Relatorios)
            .WithMany(r => r.Fotos)
            .HasForeignKey(f => f.RelatorioId);

            modelBuilder.Entity<Terrenos>().HasData(
                new Terrenos { Id = 1, Nome = "Casa do Baixo Quiriri", Area = 5000, Matricula = 767375, Proprietaria = "Hacasa", Cidade = "Joinville", Latitude = -26.3044, Longitude = -48.8487, MarcadoComoImportante = false },
                new Terrenos { Id = 2, Nome = "Casa do Alto Quiriri", Area = 10000, Matricula = 6537523, Proprietaria = "Ciser", Cidade = "Campo alegre", Latitude = -22.9068, Longitude = -43.1729, MarcadoComoImportante = false },
                new Terrenos { Id = 3, Nome = "Terreno Loteamento Espinheiro", Area = 1000, Matricula = 59375237, Proprietaria = "Hacasa", Cidade = "Sao Francisco do Sul", Latitude = 40.7128, Longitude = -74.0060, MarcadoComoImportante = false },
                new Terrenos { Id = 4, Nome = "Terreno Loteamento Boa Vista", Area = 5000, Matricula = 837539, Proprietaria = "Ciser", Cidade = "Joinville", Latitude = 48.8566, Longitude = 2.3522, MarcadoComoImportante = false },
                new Terrenos { Id = 5, Nome = "Terreno Loteamento America", Area = 100, Matricula = 31398375, Proprietaria = "Ciser", Cidade = "Sao Francisco do Sul", Latitude = 35.6895, Longitude = 139.6917, MarcadoComoImportante = false },
                new Terrenos { Id = 6, Nome = "Chacara Campo Alegre", Area = 50000, Matricula = 2697867, Proprietaria = "Parana", Cidade = "Campo alegre", Latitude = -33.8688, Longitude = 151.2093, MarcadoComoImportante = false },
                new Terrenos { Id = 7, Nome = "Sede Ciser", Area = 8000, Matricula = 1785, Proprietaria = "Hacasa", Cidade = "Joinville", Latitude = 51.5074, Longitude = -0.1278, MarcadoComoImportante = false },

                new Terrenos { Id = 8, Nome = "Fazenda Boa Vista", Area = 12000, Matricula = 2451, Proprietaria = "AgroSul", Cidade = "Londrina", Latitude = 34.0522, Longitude = -118.2437, MarcadoComoImportante = false },
                new Terrenos { Id = 9, Nome = "Sítio Recanto Verde", Area = 4500, Matricula = 3124, Proprietaria = "VerdeVale", Cidade = "Maringá", Latitude = 55.7558, Longitude = 37.6173, MarcadoComoImportante = false },
                new Terrenos { Id = 10, Nome = "Chácara Santa Luzia", Area = 3000, Matricula = 1987, Proprietaria = "Família Souza", Cidade = "Curitiba", Latitude = 41.9028, Longitude = 12.4964, MarcadoComoImportante = false },
                new Terrenos { Id = 11, Nome = "Fazenda Horizonte", Area = 25000, Matricula = 5562, Proprietaria = "TerraNova", Cidade = "Campo Grande", Latitude = 19.4326, Longitude = -99.1332, MarcadoComoImportante = false },
                new Terrenos { Id = 12, Nome = "Sítio Bela Serra", Area = 5200, Matricula = 2874, Proprietaria = "SerraAlta", Cidade = "Guarapuava", Latitude = 52.5200, Longitude = 13.4050, MarcadoComoImportante = false },
                new Terrenos { Id = 13, Nome = "Chácara Vale do Sol", Area = 3800, Matricula = 3345, Proprietaria = "ValeSul", Cidade = "Ponta Grossa", Latitude = 59.3293, Longitude = 18.0686, MarcadoComoImportante = false },
                new Terrenos { Id = 14, Nome = "Fazenda Três Rios", Area = 18000, Matricula = 6721, Proprietaria = "AgroRios", Cidade = "Cascavel", Latitude = 37.7749, Longitude = -122.4194, MarcadoComoImportante = false },
                new Terrenos { Id = 15, Nome = "Sítio Pedra Branca", Area = 6100, Matricula = 4210, Proprietaria = "PedraSul", Cidade = "Blumenau", Latitude = 31.2304, Longitude = 121.4737, MarcadoComoImportante = false },
                new Terrenos { Id = 16, Nome = "Chácara Primavera", Area = 2900, Matricula = 3891, Proprietaria = "Primavera Ltda", Cidade = "Florianópolis", Latitude = 28.6139, Longitude = 77.2090, MarcadoComoImportante = false },
                new Terrenos { Id = 17, Nome = "Fazenda Alto Alegre", Area = 22000, Matricula = 7453, Proprietaria = "Alto Agro", Cidade = "Dourados", Latitude = 50.1109, Longitude = 8.6821, MarcadoComoImportante = false },
                new Terrenos { Id = 18, Nome = "Sítio Campo Belo", Area = 4700, Matricula = 2987, Proprietaria = "Campo Forte", Cidade = "Uberlândia", Latitude = 45.4642, Longitude = 9.1900, MarcadoComoImportante = false },
                new Terrenos { Id = 19, Nome = "Chácara Estrela do Sul", Area = 3500, Matricula = 3654, Proprietaria = "Estrela Agro", Cidade = "Ribeirão Preto", Latitude = 43.6532, Longitude = -79.3832, MarcadoComoImportante = false },
                new Terrenos { Id = 20, Nome = "Fazenda Santa Helena", Area = 27000, Matricula = 8123, Proprietaria = "Helena Agropecuária", Cidade = "Goiânia", Latitude = 1.3521, Longitude = 103.8198, MarcadoComoImportante = false },
                new Terrenos { Id = 21, Nome = "Sítio Água Clara", Area = 5400, Matricula = 2765, Proprietaria = "Água Viva", Cidade = "Chapecó", Latitude = 35.6762, Longitude = 139.6503, MarcadoComoImportante = false },
                new Terrenos { Id = 22, Nome = "Chácara Monte Verde", Area = 4100, Matricula = 3498, Proprietaria = "Monte Verde Ltda", Cidade = "Poços de Caldas", Latitude = 60.1699, Longitude = 24.9384, MarcadoComoImportante = false },
                new Terrenos { Id = 23, Nome = "Fazenda Ouro Branco", Area = 31000, Matricula = 9231, Proprietaria = "Ouro Agro", Cidade = "Uberaba", Latitude = -23.5505, Longitude = -46.6333, MarcadoComoImportante = false },
                new Terrenos { Id = 24, Nome = "Sítio Lago Azul", Area = 4800, Matricula = 2574, Proprietaria = "Lago Azul Ltda", Cidade = "Joinville", Latitude = -34.6037, Longitude = -58.3816, MarcadoComoImportante = false },
                new Terrenos { Id = 25, Nome = "Chácara Boa Esperança", Area = 3300, Matricula = 3189, Proprietaria = "Esperança Rural", Cidade = "Sorocaba", Latitude = 25.2048, Longitude = 55.2708, MarcadoComoImportante = false },
                new Terrenos { Id = 26, Nome = "Fazenda Santa Rita", Area = 29000, Matricula = 8675, Proprietaria = "Santa Rita Agro", Cidade = "Palmas", Latitude = 19.0760, Longitude = 72.8777, MarcadoComoImportante = false },
                new Terrenos { Id = 27, Nome = "Sítio Encanto da Serra", Area = 5600, Matricula = 2999, Proprietaria = "Encanto Verde", Cidade = "Nova Friburgo", Latitude = 41.3851, Longitude = 2.1734, MarcadoComoImportante = false },

                new Terrenos { Id = 28, Nome = "Fazenda Rio Dourado", Area = 21000, Matricula = 9342, Proprietaria = "Rio Agro", Cidade = "Sinop", Latitude = 64.2008, Longitude = -149.4937, MarcadoComoImportante = false },
                new Terrenos { Id = 29, Nome = "Sítio Bela Vista", Area = 4300, Matricula = 2781, Proprietaria = "Bela Vista Rural", Cidade = "Itu", Latitude = -13.1631, Longitude = -72.5450, MarcadoComoImportante = false },
                new Terrenos { Id = 30, Nome = "Chácara Recanto Feliz", Area = 3200, Matricula = 3567, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí", Latitude = 64.9631, Longitude = -19.0208, MarcadoComoImportante = false },
                new Terrenos { Id = 31, Nome = "Fazenda Santa Clara", Area = 26000, Matricula = 8452, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis", Latitude = -22.9519, Longitude = -43.2105, MarcadoComoImportante = false },
                new Terrenos { Id = 32, Nome = "Sítio Vale Verde", Area = 5100, Matricula = 2643, Proprietaria = "Vale Verde Ltda", Cidade = "Passo Fundo", Latitude = 46.2276, Longitude = 2.2137, MarcadoComoImportante = false },
                new Terrenos { Id = 33, Nome = "Chácara Sol Nascente", Area = 3700, Matricula = 3894, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas", Latitude = 35.9078, Longitude = 127.7669, MarcadoComoImportante = false },
                new Terrenos { Id = 34, Nome = "Fazenda Três Lagoas", Area = 28000, Matricula = 9021, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas", Latitude = -9.1899, Longitude = -75.0152, MarcadoComoImportante = false },
                new Terrenos { Id = 35, Nome = "Sítio Pedra Azul", Area = 4900, Matricula = 2956, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins", Latitude = 56.1304, Longitude = -106.3468, MarcadoComoImportante = false },
                new Terrenos { Id = 36, Nome = "Chácara Vale Encantado", Area = 3400, Matricula = 3722, Proprietaria = "Encanto Rural", Cidade = "Atibaia", Latitude = 30.0444, Longitude = 31.2357, MarcadoComoImportante = false },
                new Terrenos { Id = 37, Nome = "Fazenda Boa Esperança", Area = 30000, Matricula = 9784, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras", Latitude = 13.7563, Longitude = 100.5018, MarcadoComoImportante = false },
                new Terrenos { Id = 38, Nome = "Sítio Água Verde", Area = 4600, Matricula = 2819, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais", Latitude = 59.9139, Longitude = 10.7522, MarcadoComoImportante = false },
                new Terrenos { Id = 39, Nome = "Chácara Serra Dourada", Area = 3600, Matricula = 3475, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis", Latitude = -17.8249, Longitude = 31.0492, MarcadoComoImportante = false },
                new Terrenos { Id = 40, Nome = "Fazenda Campo Grande", Area = 27000, Matricula = 8891, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande", Latitude = 61.5240, Longitude = 105.3188, MarcadoComoImportante = false },
                new Terrenos { Id = 41, Nome = "Sítio Vista Alegre", Area = 5200, Matricula = 2637, Proprietaria = "Vista Alegre Rural", Cidade = "Lages", Latitude = 7.8731, Longitude = 80.7718, MarcadoComoImportante = false },
                new Terrenos { Id = 42, Nome = "Chácara Morada do Sol", Area = 3100, Matricula = 3588, Proprietaria = "Morada Ltda", Cidade = "Araraquara", Latitude = 25.7617, Longitude = -80.1918, MarcadoComoImportante = false },
                new Terrenos { Id = 43, Nome = "Fazenda Santa Tereza", Area = 24000, Matricula = 8129, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá", Latitude = 50.8503, Longitude = 4.3517, MarcadoComoImportante = false },
                new Terrenos { Id = 44, Nome = "Sítio Recanto das Flores", Area = 4800, Matricula = 2991, Proprietaria = "Flores do Campo", Cidade = "Holambra", Latitude = -36.8485, Longitude = 174.7633, MarcadoComoImportante = false },
                new Terrenos { Id = 45, Nome = "Chácara Jardim das Palmeiras", Area = 3500, Matricula = 3662, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos", Latitude = 55.9533, Longitude = -3.1883, MarcadoComoImportante = false },
                new Terrenos { Id = 46, Nome = "Fazenda Vale do Rio", Area = 32000, Matricula = 9953, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz", Latitude = 35.2271, Longitude = -80.8431, MarcadoComoImportante = false },
                new Terrenos { Id = 47, Nome = "Sítio Encosta Verde", Area = 5300, Matricula = 2714, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis", Latitude = 48.2082, Longitude = 16.3738, MarcadoComoImportante = false },

                new Terrenos { Id = 48, Nome = "Fazenda Boa Vista", Area = 23000, Matricula = 9027, Proprietaria = "AgroSul", Cidade = "Londrina", Latitude = 66.1605, Longitude = -153.3691, MarcadoComoImportante = false },
                new Terrenos { Id = 49, Nome = "Sítio Bela Serra", Area = 5000, Matricula = 2841, Proprietaria = "SerraAlta", Cidade = "Guarapuava", Latitude = -45.0312, Longitude = 168.6626, MarcadoComoImportante = false },
                new Terrenos { Id = 50, Nome = "Chácara Vale do Sol", Area = 3600, Matricula = 3312, Proprietaria = "ValeSul", Cidade = "Ponta Grossa", Latitude = 64.1466, Longitude = -21.9426, MarcadoComoImportante = false },
                new Terrenos { Id = 51, Nome = "Fazenda Horizonte", Area = 25500, Matricula = 5610, Proprietaria = "TerraNova", Cidade = "Campo Grande", Latitude = 35.8617, Longitude = 104.1954, MarcadoComoImportante = false },
                new Terrenos { Id = 52, Nome = "Sítio Pedra Branca", Area = 6200, Matricula = 4268, Proprietaria = "PedraSul", Cidade = "Blumenau", Latitude = -20.3484, Longitude = 57.5522, MarcadoComoImportante = false },
                new Terrenos { Id = 53, Nome = "Chácara Primavera", Area = 3000, Matricula = 3925, Proprietaria = "Primavera Ltda", Cidade = "Florianópolis", Latitude = 53.3498, Longitude = -6.2603, MarcadoComoImportante = false },
                new Terrenos { Id = 54, Nome = "Fazenda Alto Alegre", Area = 21500, Matricula = 7489, Proprietaria = "Alto Agro", Cidade = "Dourados", Latitude = 36.2048, Longitude = 138.2529, MarcadoComoImportante = false },
                new Terrenos { Id = 55, Nome = "Sítio Campo Belo", Area = 4700, Matricula = 2971, Proprietaria = "Campo Forte", Cidade = "Uberlândia", Latitude = -8.7832, Longitude = -55.4915, MarcadoComoImportante = false },
                new Terrenos { Id = 56, Nome = "Chácara Estrela do Sul", Area = 3400, Matricula = 3620, Proprietaria = "Estrela Agro", Cidade = "Ribeirão Preto", Latitude = 56.8796, Longitude = 24.6032, MarcadoComoImportante = false },
                new Terrenos { Id = 57, Nome = "Fazenda Santa Helena", Area = 27500, Matricula = 8188, Proprietaria = "Helena Agropecuária", Cidade = "Goiânia", Latitude = 14.5995, Longitude = 120.9842, MarcadoComoImportante = false },
                new Terrenos { Id = 58, Nome = "Sítio Água Clara", Area = 5500, Matricula = 2793, Proprietaria = "Água Viva", Cidade = "Chapecó", Latitude = 59.4370, Longitude = 24.7536, MarcadoComoImportante = false },
                new Terrenos { Id = 59, Nome = "Chácara Monte Verde", Area = 4200, Matricula = 3521, Proprietaria = "Monte Verde Ltda", Cidade = "Poços de Caldas", Latitude = -1.2921, Longitude = 36.8219, MarcadoComoImportante = false },
                new Terrenos { Id = 60, Nome = "Fazenda Ouro Branco", Area = 30500, Matricula = 9277, Proprietaria = "Ouro Agro", Cidade = "Uberaba", Latitude = 50.0755, Longitude = 14.4378, MarcadoComoImportante = false },
                new Terrenos { Id = 61, Nome = "Sítio Lago Azul", Area = 4900, Matricula = 2598, Proprietaria = "Lago Azul Ltda", Cidade = "Joinville", Latitude = -22.9068, Longitude = 18.4232, MarcadoComoImportante = false },
                new Terrenos { Id = 62, Nome = "Chácara Boa Esperança", Area = 3200, Matricula = 3155, Proprietaria = "Esperança Rural", Cidade = "Sorocaba", Latitude = 61.2181, Longitude = -149.9003, MarcadoComoImportante = false },
                new Terrenos { Id = 63, Nome = "Fazenda Santa Rita", Area = 29500, Matricula = 8721, Proprietaria = "Santa Rita Agro", Cidade = "Palmas", Latitude = 33.6844, Longitude = 73.0479, MarcadoComoImportante = false },
                new Terrenos { Id = 64, Nome = "Sítio Encanto da Serra", Area = 5700, Matricula = 3012, Proprietaria = "Encanto Verde", Cidade = "Nova Friburgo", Latitude = 47.4979, Longitude = 19.0402, MarcadoComoImportante = false },
                new Terrenos { Id = 65, Nome = "Chácara Recanto Feliz", Area = 3300, Matricula = 3599, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí", Latitude = -15.7942, Longitude = -47.8822, MarcadoComoImportante = false },
                new Terrenos { Id = 66, Nome = "Fazenda Campo Grande", Area = 26800, Matricula = 8842, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande", Latitude = 55.6761, Longitude = 12.5683, MarcadoComoImportante = false },
                new Terrenos { Id = 67, Nome = "Sítio Vista Alegre", Area = 5100, Matricula = 2610, Proprietaria = "Vista Alegre Rural", Cidade = "Lages", Latitude = 37.5665, Longitude = 126.9780, MarcadoComoImportante = false },

                new Terrenos { Id = 68, Nome = "Fazenda Rio Dourado", Area = 22500, Matricula = 9365, Proprietaria = "Rio Agro", Cidade = "Sinop", Latitude = 64.9631, Longitude = -19.0208, MarcadoComoImportante = false },
                new Terrenos { Id = 69, Nome = "Sítio Bela Vista", Area = 4400, Matricula = 2798, Proprietaria = "Bela Vista Rural", Cidade = "Itu", Latitude = -33.9249, Longitude = 18.4241, MarcadoComoImportante = false },
                new Terrenos { Id = 70, Nome = "Chácara Sol Nascente", Area = 3800, Matricula = 3912, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas", Latitude = 60.4720, Longitude = 8.4689, MarcadoComoImportante = false },
                new Terrenos { Id = 71, Nome = "Fazenda Três Lagoas", Area = 28500, Matricula = 9054, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas", Latitude = 9.0820, Longitude = 8.6753, MarcadoComoImportante = false },
                new Terrenos { Id = 72, Nome = "Sítio Pedra Azul", Area = 5000, Matricula = 2983, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins", Latitude = 56.2639, Longitude = 9.5018, MarcadoComoImportante = false },
                new Terrenos { Id = 73, Nome = "Chácara Vale Encantado", Area = 3500, Matricula = 3740, Proprietaria = "Encanto Rural", Cidade = "Atibaia", Latitude = -12.0464, Longitude = -77.0428, MarcadoComoImportante = false },
                new Terrenos { Id = 74, Nome = "Fazenda Boa Esperança", Area = 30500, Matricula = 9802, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras", Latitude = 35.6892, Longitude = 51.3890, MarcadoComoImportante = false },
                new Terrenos { Id = 75, Nome = "Sítio Água Verde", Area = 4700, Matricula = 2835, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais", Latitude = 41.0082, Longitude = 28.9784, MarcadoComoImportante = false },
                new Terrenos { Id = 76, Nome = "Chácara Serra Dourada", Area = 3650, Matricula = 3492, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis", Latitude = 59.9343, Longitude = 30.3351, MarcadoComoImportante = false },
                new Terrenos { Id = 77, Nome = "Fazenda Santa Clara", Area = 26000, Matricula = 8477, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis", Latitude = 13.0827, Longitude = 80.2707, MarcadoComoImportante = false },
                new Terrenos { Id = 78, Nome = "Sítio Vale Verde", Area = 5200, Matricula = 2661, Proprietaria = "Vale Verde Ltda", Cidade = "Passo Fundo", Latitude = 52.3676, Longitude = 4.9041, MarcadoComoImportante = false },
                new Terrenos { Id = 79, Nome = "Chácara Morada do Sol", Area = 3200, Matricula = 3604, Proprietaria = "Morada Ltda", Cidade = "Araraquara", Latitude = 25.2760, Longitude = 55.2962, MarcadoComoImportante = false },
                new Terrenos { Id = 80, Nome = "Fazenda Santa Tereza", Area = 24500, Matricula = 8150, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá", Latitude = -6.2088, Longitude = 106.8456, MarcadoComoImportante = false },
                new Terrenos { Id = 81, Nome = "Sítio Recanto das Flores", Area = 4900, Matricula = 3007, Proprietaria = "Flores do Campo", Cidade = "Holambra", Latitude = 50.1109, Longitude = 8.6821, MarcadoComoImportante = false },
                new Terrenos { Id = 82, Nome = "Chácara Jardim das Palmeiras", Area = 3600, Matricula = 3688, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos", Latitude = 59.3293, Longitude = 18.0686, MarcadoComoImportante = false },
                new Terrenos { Id = 83, Nome = "Fazenda Vale do Rio", Area = 32500, Matricula = 9981, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz", Latitude = 19.0760, Longitude = 72.8777, MarcadoComoImportante = false },
                new Terrenos { Id = 84, Nome = "Sítio Encosta Verde", Area = 5400, Matricula = 2730, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis", Latitude = 55.7558, Longitude = 37.6173, MarcadoComoImportante = false },
                new Terrenos { Id = 85, Nome = "Chácara Recanto Verde", Area = 3300, Matricula = 3615, Proprietaria = "VerdeVale", Cidade = "Maringá", Latitude = 37.7749, Longitude = -122.4194, MarcadoComoImportante = false },
                new Terrenos { Id = 86, Nome = "Fazenda Três Rios", Area = 18200, Matricula = 6754, Proprietaria = "AgroRios", Cidade = "Cascavel", Latitude = 48.8566, Longitude = 2.3522, MarcadoComoImportante = false },
                new Terrenos { Id = 87, Nome = "Sítio Água Clara", Area = 5600, Matricula = 3033, Proprietaria = "Água Viva", Cidade = "Chapecó", Latitude = 35.6762, Longitude = 139.6503, MarcadoComoImportante = false },

                new Terrenos { Id = 88, Nome = "Fazenda Horizonte", Area = 26000, Matricula = 5638, Proprietaria = "TerraNova", Cidade = "Campo Grande", Latitude = 46.8182, Longitude = 8.2275, MarcadoComoImportante = false },
                new Terrenos { Id = 89, Nome = "Sítio Pedra Branca", Area = 6300, Matricula = 4285, Proprietaria = "PedraSul", Cidade = "Blumenau", Latitude = -17.7134, Longitude = 178.0650, MarcadoComoImportante = false },
                new Terrenos { Id = 90, Nome = "Chácara Primavera", Area = 3100, Matricula = 3950, Proprietaria = "Primavera Ltda", Cidade = "Florianópolis", Latitude = 64.1355, Longitude = -21.8954, MarcadoComoImportante = false },
                new Terrenos { Id = 91, Nome = "Fazenda Alto Alegre", Area = 22000, Matricula = 7521, Proprietaria = "Alto Agro", Cidade = "Dourados", Latitude = 52.5200, Longitude = 13.4050, MarcadoComoImportante = false },
                new Terrenos { Id = 92, Nome = "Sítio Campo Belo", Area = 4800, Matricula = 2995, Proprietaria = "Campo Forte", Cidade = "Uberlândia", Latitude = -22.9519, Longitude = -43.2105, MarcadoComoImportante = false },
                new Terrenos { Id = 93, Nome = "Chácara Estrela do Sul", Area = 3500, Matricula = 3641, Proprietaria = "Estrela Agro", Cidade = "Ribeirão Preto", Latitude = 41.3851, Longitude = 2.1734, MarcadoComoImportante = false },
                new Terrenos { Id = 94, Nome = "Fazenda Santa Helena", Area = 28000, Matricula = 8205, Proprietaria = "Helena Agropecuária", Cidade = "Goiânia", Latitude = 35.6762, Longitude = 139.6503, MarcadoComoImportante = false },
                new Terrenos { Id = 95, Nome = "Sítio Água Clara", Area = 5700, Matricula = 3050, Proprietaria = "Água Viva", Cidade = "Chapecó", Latitude = 55.7558, Longitude = 37.6173, MarcadoComoImportante = false },
                new Terrenos { Id = 96, Nome = "Chácara Monte Verde", Area = 4300, Matricula = 3544, Proprietaria = "Monte Verde Ltda", Cidade = "Poços de Caldas", Latitude = 37.7749, Longitude = -122.4194, MarcadoComoImportante = false },
                new Terrenos { Id = 97, Nome = "Fazenda Ouro Branco", Area = 31000, Matricula = 9302, Proprietaria = "Ouro Agro", Cidade = "Uberaba", Latitude = 48.8566, Longitude = 2.3522, MarcadoComoImportante = false },
                new Terrenos { Id = 98, Nome = "Sítio Lago Azul", Area = 5000, Matricula = 2620, Proprietaria = "Lago Azul Ltda", Cidade = "Joinville", Latitude = -33.8688, Longitude = 151.2093, MarcadoComoImportante = false },
                new Terrenos { Id = 99, Nome = "Chácara Boa Esperança", Area = 3400, Matricula = 3180, Proprietaria = "Esperança Rural", Cidade = "Sorocaba", Latitude = 51.5074, Longitude = -0.1278, MarcadoComoImportante = false },
                new Terrenos { Id = 100, Nome = "Fazenda Santa Rita", Area = 30000, Matricula = 8750, Proprietaria = "Santa Rita Agro", Cidade = "Palmas", Latitude = 40.7128, Longitude = -74.0060, MarcadoComoImportante = false },
                new Terrenos { Id = 101, Nome = "Sítio Encanto da Serra", Area = 5800, Matricula = 3072, Proprietaria = "Encanto Verde", Cidade = "Nova Friburgo", Latitude = 34.0522, Longitude = -118.2437, MarcadoComoImportante = false },
                new Terrenos { Id = 102, Nome = "Chácara Recanto Feliz", Area = 3500, Matricula = 3628, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí", Latitude = 1.3521, Longitude = 103.8198, MarcadoComoImportante = false },
                new Terrenos { Id = 103, Nome = "Fazenda Campo Grande", Area = 27500, Matricula = 8870, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande", Latitude = 35.6895, Longitude = 139.6917, MarcadoComoImportante = false },
                new Terrenos { Id = 104, Nome = "Sítio Vista Alegre", Area = 5200, Matricula = 2630, Proprietaria = "Vista Alegre Rural", Cidade = "Lages", Latitude = 41.9028, Longitude = 12.4964, MarcadoComoImportante = false },
                new Terrenos { Id = 105, Nome = "Chácara Morada do Sol", Area = 3300, Matricula = 3639, Proprietaria = "Morada Ltda", Cidade = "Araraquara", Latitude = 19.4326, Longitude = -99.1332, MarcadoComoImportante = false },
                new Terrenos { Id = 106, Nome = "Fazenda Santa Tereza", Area = 25000, Matricula = 8182, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá", Latitude = 52.5200, Longitude = 13.4050, MarcadoComoImportante = false },
                new Terrenos { Id = 107, Nome = "Sítio Recanto das Flores", Area = 5000, Matricula = 3095, Proprietaria = "Flores do Campo", Cidade = "Holambra", Latitude = 59.3293, Longitude = 18.0686, MarcadoComoImportante = false },

                new Terrenos { Id = 108, Nome = "Fazenda Boa Vista", Area = 24000, Matricula = 9842, Proprietaria = "AgroSul", Cidade = "Londrina", Latitude = 63.8258, Longitude = -149.4937, MarcadoComoImportante = false },
                new Terrenos { Id = 109, Nome = "Sítio Bela Serra", Area = 5100, Matricula = 2888, Proprietaria = "SerraAlta", Cidade = "Guarapuava", Latitude = -54.8019, Longitude = -68.3030, MarcadoComoImportante = false },
                new Terrenos { Id = 110, Nome = "Chácara Vale do Sol", Area = 3700, Matricula = 3360, Proprietaria = "ValeSul", Cidade = "Ponta Grossa", Latitude = 71.7069, Longitude = -42.6043, MarcadoComoImportante = false },
                new Terrenos { Id = 111, Nome = "Fazenda Horizonte", Area = 26500, Matricula = 5689, Proprietaria = "TerraNova", Cidade = "Campo Grande", Latitude = 23.6345, Longitude = -102.5528, MarcadoComoImportante = false },
                new Terrenos { Id = 112, Nome = "Sítio Pedra Branca", Area = 6400, Matricula = 4310, Proprietaria = "PedraSul", Cidade = "Blumenau", Latitude = 64.2008, Longitude = -51.6780, MarcadoComoImportante = false },
                new Terrenos { Id = 113, Nome = "Chácara Primavera", Area = 3200, Matricula = 3982, Proprietaria = "Primavera Ltda", Cidade = "Florianópolis", Latitude = 78.2232, Longitude = 15.6469, MarcadoComoImportante = false },
                new Terrenos { Id = 114, Nome = "Fazenda Alto Alegre", Area = 22500, Matricula = 7560, Proprietaria = "Alto Agro", Cidade = "Dourados", Latitude = -25.2744, Longitude = 133.7751, MarcadoComoImportante = false },
                new Terrenos { Id = 115, Nome = "Sítio Campo Belo", Area = 4900, Matricula = 3011, Proprietaria = "Campo Forte", Cidade = "Uberlândia", Latitude = 60.1282, Longitude = 18.6435, MarcadoComoImportante = false },
                new Terrenos { Id = 116, Nome = "Chácara Estrela do Sul", Area = 3600, Matricula = 3678, Proprietaria = "Estrela Agro", Cidade = "Ribeirão Preto", Latitude = 39.9042, Longitude = 116.4074, MarcadoComoImportante = false },
                new Terrenos { Id = 117, Nome = "Fazenda Santa Helena", Area = 28500, Matricula = 8239, Proprietaria = "Helena Agropecuária", Cidade = "Goiânia", Latitude = 55.3781, Longitude = -3.4360, MarcadoComoImportante = false },
                new Terrenos { Id = 118, Nome = "Sítio Água Clara", Area = 5800, Matricula = 3108, Proprietaria = "Água Viva", Cidade = "Chapecó", Latitude = -13.2543, Longitude = 34.3015, MarcadoComoImportante = false },
                new Terrenos { Id = 119, Nome = "Chácara Monte Verde", Area = 4400, Matricula = 3570, Proprietaria = "Monte Verde Ltda", Cidade = "Poços de Caldas", Latitude = 46.2276, Longitude = 2.2137, MarcadoComoImportante = false },
                new Terrenos { Id = 120, Nome = "Fazenda Ouro Branco", Area = 31500, Matricula = 9350, Proprietaria = "Ouro Agro", Cidade = "Uberaba", Latitude = 35.8617, Longitude = 104.1954, MarcadoComoImportante = false },
                new Terrenos { Id = 121, Nome = "Sítio Lago Azul", Area = 5100, Matricula = 2655, Proprietaria = "Lago Azul Ltda", Cidade = "Joinville", Latitude = -30.5595, Longitude = 22.9375, MarcadoComoImportante = false },
                new Terrenos { Id = 122, Nome = "Chácara Boa Esperança", Area = 3500, Matricula = 3202, Proprietaria = "Esperança Rural", Cidade = "Sorocaba", Latitude = 61.9241, Longitude = 25.7482, MarcadoComoImportante = false },
                new Terrenos { Id = 123, Nome = "Fazenda Santa Rita", Area = 30500, Matricula = 8799, Proprietaria = "Santa Rita Agro", Cidade = "Palmas", Latitude = 21.1619, Longitude = -86.8515, MarcadoComoImportante = false },
                new Terrenos { Id = 124, Nome = "Sítio Encanto da Serra", Area = 5900, Matricula = 3125, Proprietaria = "Encanto Verde", Cidade = "Nova Friburgo", Latitude = 50.9375, Longitude = 6.9603, MarcadoComoImportante = false },
                new Terrenos { Id = 125, Nome = "Chácara Recanto Feliz", Area = 3600, Matricula = 3666, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí", Latitude = 13.4125, Longitude = 103.8667, MarcadoComoImportante = false },
                new Terrenos { Id = 126, Nome = "Fazenda Campo Grande", Area = 28000, Matricula = 8915, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande", Latitude = 59.9139, Longitude = 10.7522, MarcadoComoImportante = false },
                new Terrenos { Id = 127, Nome = "Sítio Vista Alegre", Area = 5300, Matricula = 2668, Proprietaria = "Vista Alegre Rural", Cidade = "Lages", Latitude = -22.3285, Longitude = 24.6849, MarcadoComoImportante = false },

                new Terrenos { Id = 128, Nome = "Chácara Morada do Sol", Area = 3400, Matricula = 3695, Proprietaria = "Morada Ltda", Cidade = "Araraquara", Latitude = 66.5039, Longitude = 25.7294, MarcadoComoImportante = false },
                new Terrenos { Id = 129, Nome = "Fazenda Santa Tereza", Area = 25500, Matricula = 8221, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá", Latitude = -23.4425, Longitude = -58.4438, MarcadoComoImportante = false },
                new Terrenos { Id = 130, Nome = "Sítio Recanto das Flores", Area = 5100, Matricula = 3133, Proprietaria = "Flores do Campo", Cidade = "Holambra", Latitude = 64.1835, Longitude = -51.7216, MarcadoComoImportante = false },
                new Terrenos { Id = 131, Nome = "Chácara Jardim das Palmeiras", Area = 3700, Matricula = 3710, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos", Latitude = 35.1796, Longitude = 129.0756, MarcadoComoImportante = false },
                new Terrenos { Id = 132, Nome = "Fazenda Vale do Rio", Area = 33000, Matricula = 10012, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz", Latitude = 56.4907, Longitude = -4.2026, MarcadoComoImportante = false },
                new Terrenos { Id = 133, Nome = "Sítio Encosta Verde", Area = 5500, Matricula = 2755, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis", Latitude = -15.3875, Longitude = 28.3228, MarcadoComoImportante = false },
                new Terrenos { Id = 134, Nome = "Chácara Recanto Verde", Area = 3400, Matricula = 3640, Proprietaria = "VerdeVale", Cidade = "Maringá", Latitude = 43.2389, Longitude = 76.8897, MarcadoComoImportante = false },
                new Terrenos { Id = 135, Nome = "Fazenda Três Rios", Area = 18500, Matricula = 6788, Proprietaria = "AgroRios", Cidade = "Cascavel", Latitude = 61.1322, Longitude = -149.8940, MarcadoComoImportante = false },
                new Terrenos { Id = 136, Nome = "Sítio Água Clara", Area = 6000, Matricula = 3159, Proprietaria = "Água Viva", Cidade = "Chapecó", Latitude = 52.2297, Longitude = 21.0122, MarcadoComoImportante = false },
                new Terrenos { Id = 137, Nome = "Chácara Sol Nascente", Area = 3900, Matricula = 3935, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas", Latitude = -3.4653, Longitude = -62.2159, MarcadoComoImportante = false },
                new Terrenos { Id = 138, Nome = "Fazenda Três Lagoas", Area = 29000, Matricula = 9089, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas", Latitude = 55.8642, Longitude = -4.2518, MarcadoComoImportante = false },
                new Terrenos { Id = 139, Nome = "Sítio Pedra Azul", Area = 5200, Matricula = 3008, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins", Latitude = 46.2044, Longitude = 6.1432, MarcadoComoImportante = false },
                new Terrenos { Id = 140, Nome = "Chácara Vale Encantado", Area = 3600, Matricula = 3762, Proprietaria = "Encanto Rural", Cidade = "Atibaia", Latitude = 35.9078, Longitude = 14.5125, MarcadoComoImportante = false },
                new Terrenos { Id = 141, Nome = "Fazenda Boa Esperança", Area = 31000, Matricula = 9833, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras", Latitude = 18.1096, Longitude = -77.2975, MarcadoComoImportante = false },
                new Terrenos { Id = 142, Nome = "Sítio Água Verde", Area = 4800, Matricula = 2860, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais", Latitude = 50.4501, Longitude = 30.5234, MarcadoComoImportante = false },
                new Terrenos { Id = 143, Nome = "Chácara Serra Dourada", Area = 3700, Matricula = 3515, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis", Latitude = 14.7167, Longitude = -17.4677, MarcadoComoImportante = false },
                new Terrenos { Id = 144, Nome = "Fazenda Santa Clara", Area = 26500, Matricula = 8505, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis", Latitude = 59.9139, Longitude = 10.7522, MarcadoComoImportante = false },
                new Terrenos { Id = 145, Nome = "Sítio Vale Verde", Area = 5300, Matricula = 2689, Proprietaria = "Vale Verde Ltda", Cidade = "Passo Fundo", Latitude = -26.2041, Longitude = 28.0473, MarcadoComoImportante = false },
                new Terrenos { Id = 146, Nome = "Chácara Recanto Feliz", Area = 3700, Matricula = 3685, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí", Latitude = 47.3769, Longitude = 8.5417, MarcadoComoImportante = false },
                new Terrenos { Id = 147, Nome = "Fazenda Campo Grande", Area = 28500, Matricula = 8950, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande", Latitude = 25.7617, Longitude = -80.1918, MarcadoComoImportante = false },

                new Terrenos { Id = 148, Nome = "Sítio Vista Alegre", Area = 5400, Matricula = 2705, Proprietaria = "Vista Alegre Rural", Cidade = "Lages", Latitude = 64.8378, Longitude = -147.7164, MarcadoComoImportante = false },
                new Terrenos { Id = 149, Nome = "Chácara Morada do Sol", Area = 3500, Matricula = 3728, Proprietaria = "Morada Ltda", Cidade = "Araraquara", Latitude = -12.4634, Longitude = 130.8456, MarcadoComoImportante = false },
                new Terrenos { Id = 150, Nome = "Fazenda Santa Tereza", Area = 26000, Matricula = 8254, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá", Latitude = 64.1265, Longitude = -21.8174, MarcadoComoImportante = false },
                new Terrenos { Id = 151, Nome = "Sítio Recanto das Flores", Area = 5200, Matricula = 3167, Proprietaria = "Flores do Campo", Cidade = "Holambra", Latitude = 35.2271, Longitude = -80.8431, MarcadoComoImportante = false },
                new Terrenos { Id = 152, Nome = "Chácara Jardim das Palmeiras", Area = 3800, Matricula = 3739, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos", Latitude = 52.3676, Longitude = 4.9041, MarcadoComoImportante = false },
                new Terrenos { Id = 153, Nome = "Fazenda Vale do Rio", Area = 33500, Matricula = 10045, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz", Latitude = -34.9285, Longitude = 138.6007, MarcadoComoImportante = false },
                new Terrenos { Id = 154, Nome = "Sítio Encosta Verde", Area = 5600, Matricula = 2780, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis", Latitude = 43.6532, Longitude = -79.3832, MarcadoComoImportante = false },
                new Terrenos { Id = 155, Nome = "Chácara Recanto Verde", Area = 3500, Matricula = 3661, Proprietaria = "VerdeVale", Cidade = "Maringá", Latitude = 60.1699, Longitude = 24.9384, MarcadoComoImportante = false },
                new Terrenos { Id = 156, Nome = "Fazenda Três Rios", Area = 19000, Matricula = 6812, Proprietaria = "AgroRios", Cidade = "Cascavel", Latitude = -22.9068, Longitude = 18.4232, MarcadoComoImportante = false },
                new Terrenos { Id = 157, Nome = "Sítio Água Clara", Area = 6100, Matricula = 3184, Proprietaria = "Água Viva", Cidade = "Chapecó", Latitude = 41.0082, Longitude = 28.9784, MarcadoComoImportante = false },
                new Terrenos { Id = 158, Nome = "Chácara Sol Nascente", Area = 4000, Matricula = 3960, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas", Latitude = 59.3293, Longitude = 18.0686, MarcadoComoImportante = false },
                new Terrenos { Id = 159, Nome = "Fazenda Três Lagoas", Area = 29500, Matricula = 9120, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas", Latitude = 19.4326, Longitude = -99.1332, MarcadoComoImportante = false },
                new Terrenos { Id = 160, Nome = "Sítio Pedra Azul", Area = 5300, Matricula = 3035, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins", Latitude = 55.7558, Longitude = 37.6173, MarcadoComoImportante = false },
                new Terrenos { Id = 161, Nome = "Chácara Vale Encantado", Area = 3700, Matricula = 3788, Proprietaria = "Encanto Rural", Cidade = "Atibaia", Latitude = 35.6762, Longitude = 139.6503, MarcadoComoImportante = false },
                new Terrenos { Id = 162, Nome = "Fazenda Boa Esperança", Area = 31500, Matricula = 9860, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras", Latitude = 48.8566, Longitude = 2.3522, MarcadoComoImportante = false },
                new Terrenos { Id = 163, Nome = "Sítio Água Verde", Area = 4900, Matricula = 2884, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais", Latitude = 37.7749, Longitude = -122.4194, MarcadoComoImportante = false },
                new Terrenos { Id = 164, Nome = "Chácara Serra Dourada", Area = 3800, Matricula = 3540, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis", Latitude = 1.3521, Longitude = 103.8198, MarcadoComoImportante = false },
                new Terrenos { Id = 165, Nome = "Fazenda Santa Clara", Area = 27000, Matricula = 8533, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis", Latitude = 51.5074, Longitude = -0.1278, MarcadoComoImportante = false },
                new Terrenos { Id = 166, Nome = "Sítio Vale Verde", Area = 5400, Matricula = 2715, Proprietaria = "Vale Verde Ltda", Cidade = "Passo Fundo", Latitude = -33.8688, Longitude = 151.2093, MarcadoComoImportante = false },
                new Terrenos { Id = 167, Nome = "Chácara Recanto Feliz", Area = 3800, Matricula = 3709, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí", Latitude = 40.7128, Longitude = -74.0060, MarcadoComoImportante = false },

                new Terrenos { Id = 168, Nome = "Fazenda Campo Grande", Area = 29000, Matricula = 8982, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande", Latitude = 66.0000, Longitude = 30.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 169, Nome = "Sítio Vista Alegre", Area = 5500, Matricula = 2738, Proprietaria = "Vista Alegre Rural", Cidade = "Lages", Latitude = -35.0000, Longitude = -70.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 170, Nome = "Chácara Morada do Sol", Area = 3600, Matricula = 3756, Proprietaria = "Morada Ltda", Cidade = "Araraquara", Latitude = 10.0000, Longitude = 20.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 171, Nome = "Fazenda Santa Tereza", Area = 26500, Matricula = 8289, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá", Latitude = -10.0000, Longitude = 100.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 172, Nome = "Sítio Recanto das Flores", Area = 5300, Matricula = 3199, Proprietaria = "Flores do Campo", Cidade = "Holambra", Latitude = 35.0000, Longitude = -10.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 173, Nome = "Chácara Jardim das Palmeiras", Area = 3900, Matricula = 3768, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos", Latitude = 48.0000, Longitude = 14.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 174, Nome = "Fazenda Vale do Rio", Area = 34000, Matricula = 10078, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz", Latitude = -20.0000, Longitude = 130.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 175, Nome = "Sítio Encosta Verde", Area = 5700, Matricula = 2804, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis", Latitude = 55.0000, Longitude = -3.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 176, Nome = "Chácara Recanto Verde", Area = 3600, Matricula = 3684, Proprietaria = "VerdeVale", Cidade = "Maringá", Latitude = -15.0000, Longitude = -47.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 177, Nome = "Fazenda Três Rios", Area = 19500, Matricula = 6845, Proprietaria = "AgroRios", Cidade = "Cascavel", Latitude = 60.0000, Longitude = 90.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 178, Nome = "Sítio Água Clara", Area = 6200, Matricula = 3210, Proprietaria = "Água Viva", Cidade = "Chapecó", Latitude = -25.0000, Longitude = 25.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 179, Nome = "Chácara Sol Nascente", Area = 4100, Matricula = 3987, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas", Latitude = 30.0000, Longitude = 120.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 180, Nome = "Fazenda Três Lagoas", Area = 30000, Matricula = 9156, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas", Latitude = -30.0000, Longitude = -60.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 181, Nome = "Sítio Pedra Azul", Area = 5400, Matricula = 3062, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins", Latitude = 45.0000, Longitude = 45.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 182, Nome = "Chácara Vale Encantado", Area = 3800, Matricula = 3815, Proprietaria = "Encanto Rural", Cidade = "Atibaia", Latitude = -5.0000, Longitude = -30.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 183, Nome = "Fazenda Boa Esperança", Area = 32000, Matricula = 9894, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras", Latitude = 20.0000, Longitude = -80.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 184, Nome = "Sítio Água Verde", Area = 5000, Matricula = 2907, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais", Latitude = 65.0000, Longitude = 60.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 185, Nome = "Chácara Serra Dourada", Area = 3900, Matricula = 3566, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis", Latitude = -40.0000, Longitude = 140.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 186, Nome = "Fazenda Santa Clara", Area = 27500, Matricula = 8570, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis", Latitude = 15.0000, Longitude = -100.0000, MarcadoComoImportante = false },
                new Terrenos { Id = 187, Nome = "Sítio Vale Verde", Area = 5500, Matricula = 2742, Proprietaria = "Vale Verde Ltda", Cidade = "Passo Fundo", Latitude = -45.0000, Longitude = 10.0000, MarcadoComoImportante = false },

                new Terrenos { Id = 188, Nome = "Chácara Recanto Feliz", Area = 3900, Matricula = 3735, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí", Latitude = 12.9716, Longitude = 77.5946, MarcadoComoImportante = false },
                new Terrenos { Id = 189, Nome = "Fazenda Campo Grande", Area = 29500, Matricula = 9010, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande", Latitude = -33.4489, Longitude = -70.6693, MarcadoComoImportante = false },
                new Terrenos { Id = 190, Nome = "Sítio Vista Alegre", Area = 5600, Matricula = 2766, Proprietaria = "Vista Alegre Rural", Cidade = "Lages", Latitude = 64.9631, Longitude = -19.0208, MarcadoComoImportante = false },
                new Terrenos { Id = 191, Nome = "Chácara Morada do Sol", Area = 3700, Matricula = 3780, Proprietaria = "Morada Ltda", Cidade = "Araraquara", Latitude = 35.6895, Longitude = 139.6917, MarcadoComoImportante = false },
                new Terrenos { Id = 192, Nome = "Fazenda Santa Tereza", Area = 27000, Matricula = 8320, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá", Latitude = 48.2082, Longitude = 16.3738, MarcadoComoImportante = false },
                new Terrenos { Id = 193, Nome = "Sítio Recanto das Flores", Area = 5400, Matricula = 3228, Proprietaria = "Flores do Campo", Cidade = "Holambra", Latitude = -26.2041, Longitude = 28.0473, MarcadoComoImportante = false },
                new Terrenos { Id = 194, Nome = "Chácara Jardim das Palmeiras", Area = 4000, Matricula = 3799, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos", Latitude = 50.8503, Longitude = 4.3517, MarcadoComoImportante = false },
                new Terrenos { Id = 195, Nome = "Fazenda Vale do Rio", Area = 34500, Matricula = 10105, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz", Latitude = -34.6037, Longitude = -58.3816, MarcadoComoImportante = false },
                new Terrenos { Id = 196, Nome = "Sítio Encosta Verde", Area = 5800, Matricula = 2831, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis", Latitude = 59.9139, Longitude = 10.7522, MarcadoComoImportante = false },
                new Terrenos { Id = 197, Nome = "Chácara Recanto Verde", Area = 3700, Matricula = 3702, Proprietaria = "VerdeVale", Cidade = "Maringá", Latitude = 13.7563, Longitude = 100.5018, MarcadoComoImportante = false },
                new Terrenos { Id = 198, Nome = "Fazenda Três Rios", Area = 20000, Matricula = 6879, Proprietaria = "AgroRios", Cidade = "Cascavel", Latitude = 55.9533, Longitude = -3.1883, MarcadoComoImportante = false },
                new Terrenos { Id = 199, Nome = "Sítio Água Clara", Area = 6300, Matricula = 3244, Proprietaria = "Água Viva", Cidade = "Chapecó", Latitude = 25.2048, Longitude = 55.2708, MarcadoComoImportante = false },
                new Terrenos { Id = 200, Nome = "Chácara Sol Nascente", Area = 4200, Matricula = 4012, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas", Latitude = 41.0082, Longitude = 28.9784, MarcadoComoImportante = false },
                new Terrenos { Id = 201, Nome = "Fazenda Três Lagoas", Area = 30500, Matricula = 9188, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas", Latitude = 60.1699, Longitude = 24.9384, MarcadoComoImportante = false },
                new Terrenos { Id = 202, Nome = "Sítio Pedra Azul", Area = 5500, Matricula = 3089, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins", Latitude = -36.8485, Longitude = 174.7633, MarcadoComoImportante = false },
                new Terrenos { Id = 203, Nome = "Chácara Vale Encantado", Area = 3900, Matricula = 3840, Proprietaria = "Encanto Rural", Cidade = "Atibaia", Latitude = 52.5200, Longitude = 13.4050, MarcadoComoImportante = false },
                new Terrenos { Id = 204, Nome = "Fazenda Boa Esperança", Area = 32500, Matricula = 9925, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras", Latitude = 19.4326, Longitude = -99.1332, MarcadoComoImportante = false },
                new Terrenos { Id = 205, Nome = "Sítio Água Verde", Area = 5100, Matricula = 2930, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais", Latitude = 35.6762, Longitude = 139.6503, MarcadoComoImportante = false },
                new Terrenos { Id = 206, Nome = "Chácara Serra Dourada", Area = 4000, Matricula = 3592, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis", Latitude = -22.9519, Longitude = -43.2105, MarcadoComoImportante = false },
                new Terrenos { Id = 207, Nome = "Fazenda Santa Clara", Area = 28000, Matricula = 8602, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis", Latitude = 37.7749, Longitude = -122.4194, MarcadoComoImportante = false }

                );
        }
    }
}

