using Microsoft.EntityFrameworkCore;
using Sistema.Modelos;

namespace Sistema.Repository

{
    public class MeuDbContext : DbContext
    {
        public MeuDbContext(DbContextOptions<MeuDbContext> options) : base(options) { }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<Terrenos> Terrenos { get; set; }
        public DbSet<Relatorios> Relatorios { get; set; }
        public DbSet<Foto> Foto { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Foto>()
            .HasOne(f => f.Relatorios)
            .WithMany(r => r.Fotos)
            .HasForeignKey(f => f.RelatorioId);

            modelBuilder.Entity<Terrenos>().HasData(
                new Terrenos { Id = 1, Nome = "Casa do Baixo Quiriri", Area = 5000, Matricula = 767375, Proprietaria = "Hacasa", Cidade = "Joinville" },
                new Terrenos { Id = 2, Nome = "Casa do Alto Quiriri", Area = 10000, Matricula = 6537523, Proprietaria = "Ciser", Cidade = "Campo alegre" },
                new Terrenos { Id = 3, Nome = "Terreno Loteamento Espinheiro", Area = 1000, Matricula = 59375237, Proprietaria = "Hacasa", Cidade = "Sao Francisco do Sul" },
                new Terrenos { Id = 4, Nome = "Terreno Loteamento Boa Vista", Area = 5000, Matricula = 837539, Proprietaria = "Ciser", Cidade = "Joinville" },
                new Terrenos { Id = 5, Nome = "Terreno Loteamento America", Area = 100, Matricula = 31398375, Proprietaria = "Ciser", Cidade = "Sao Francisco do Sul" },
                new Terrenos { Id = 6, Nome = "Chacara Campo Alegre", Area = 50000, Matricula = 2697867, Proprietaria = "Parana", Cidade = "Campo alegre" },
                new Terrenos { Id = 7, Nome = "Sede Ciser", Area = 8000, Matricula = 1785, Proprietaria = "Hacasa", Cidade = "Joinville" },

                new Terrenos { Id = 8, Nome = "Fazenda Boa Vista", Area = 12000, Matricula = 2451, Proprietaria = "AgroSul", Cidade = "Londrina" },
                new Terrenos { Id = 9, Nome = "Sítio Recanto Verde", Area = 4500, Matricula = 3124, Proprietaria = "VerdeVale", Cidade = "Maringá" },
                new Terrenos { Id = 10, Nome = "Chácara Santa Luzia", Area = 3000, Matricula = 1987, Proprietaria = "Família Souza", Cidade = "Curitiba" },
                new Terrenos { Id = 11, Nome = "Fazenda Horizonte", Area = 25000, Matricula = 5562, Proprietaria = "TerraNova", Cidade = "Campo Grande" },
                new Terrenos { Id = 12, Nome = "Sítio Bela Serra", Area = 5200, Matricula = 2874, Proprietaria = "SerraAlta", Cidade = "Guarapuava" },
                new Terrenos { Id = 13, Nome = "Chácara Vale do Sol", Area = 3800, Matricula = 3345, Proprietaria = "ValeSul", Cidade = "Ponta Grossa" },
                new Terrenos { Id = 14, Nome = "Fazenda Três Rios", Area = 18000, Matricula = 6721, Proprietaria = "AgroRios", Cidade = "Cascavel" },
                new Terrenos { Id = 15, Nome = "Sítio Pedra Branca", Area = 6100, Matricula = 4210, Proprietaria = "PedraSul", Cidade = "Blumenau" },
                new Terrenos { Id = 16, Nome = "Chácara Primavera", Area = 2900, Matricula = 3891, Proprietaria = "Primavera Ltda", Cidade = "Florianópolis" },
                new Terrenos { Id = 17, Nome = "Fazenda Alto Alegre", Area = 22000, Matricula = 7453, Proprietaria = "Alto Agro", Cidade = "Dourados" },
                new Terrenos { Id = 18, Nome = "Sítio Campo Belo", Area = 4700, Matricula = 2987, Proprietaria = "Campo Forte", Cidade = "Uberlândia" },
                new Terrenos { Id = 19, Nome = "Chácara Estrela do Sul", Area = 3500, Matricula = 3654, Proprietaria = "Estrela Agro", Cidade = "Ribeirão Preto" },
                new Terrenos { Id = 20, Nome = "Fazenda Santa Helena", Area = 27000, Matricula = 8123, Proprietaria = "Helena Agropecuária", Cidade = "Goiânia" },
                new Terrenos { Id = 21, Nome = "Sítio Água Clara", Area = 5400, Matricula = 2765, Proprietaria = "Água Viva", Cidade = "Chapecó" },
                new Terrenos { Id = 22, Nome = "Chácara Monte Verde", Area = 4100, Matricula = 3498, Proprietaria = "Monte Verde Ltda", Cidade = "Poços de Caldas" },
                new Terrenos { Id = 23, Nome = "Fazenda Ouro Branco", Area = 31000, Matricula = 9231, Proprietaria = "Ouro Agro", Cidade = "Uberaba" },
                new Terrenos { Id = 24, Nome = "Sítio Lago Azul", Area = 4800, Matricula = 2574, Proprietaria = "Lago Azul Ltda", Cidade = "Joinville" },
                new Terrenos { Id = 25, Nome = "Chácara Boa Esperança", Area = 3300, Matricula = 3189, Proprietaria = "Esperança Rural", Cidade = "Sorocaba" },
                new Terrenos { Id = 26, Nome = "Fazenda Santa Rita", Area = 29000, Matricula = 8675, Proprietaria = "Santa Rita Agro", Cidade = "Palmas" },
                new Terrenos { Id = 27, Nome = "Sítio Encanto da Serra", Area = 5600, Matricula = 2999, Proprietaria = "Encanto Verde", Cidade = "Nova Friburgo" },

                new Terrenos { Id = 28, Nome = "Fazenda Rio Dourado", Area = 21000, Matricula = 9342, Proprietaria = "Rio Agro", Cidade = "Sinop" },
                new Terrenos { Id = 29, Nome = "Sítio Bela Vista", Area = 4300, Matricula = 2781, Proprietaria = "Bela Vista Rural", Cidade = "Itu" },
                new Terrenos { Id = 30, Nome = "Chácara Recanto Feliz", Area = 3200, Matricula = 3567, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí" },
                new Terrenos { Id = 31, Nome = "Fazenda Santa Clara", Area = 26000, Matricula = 8452, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis" },
                new Terrenos { Id = 32, Nome = "Sítio Vale Verde", Area = 5100, Matricula = 2643, Proprietaria = "Vale Verde Ltda", Cidade = "Passo Fundo" },
                new Terrenos { Id = 33, Nome = "Chácara Sol Nascente", Area = 3700, Matricula = 3894, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas" },
                new Terrenos { Id = 34, Nome = "Fazenda Três Lagoas", Area = 28000, Matricula = 9021, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas" },
                new Terrenos { Id = 35, Nome = "Sítio Pedra Azul", Area = 4900, Matricula = 2956, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins" },
                new Terrenos { Id = 36, Nome = "Chácara Vale Encantado", Area = 3400, Matricula = 3722, Proprietaria = "Encanto Rural", Cidade = "Atibaia" },
                new Terrenos { Id = 37, Nome = "Fazenda Boa Esperança", Area = 30000, Matricula = 9784, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras" },
                new Terrenos { Id = 38, Nome = "Sítio Água Verde", Area = 4600, Matricula = 2819, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais" },
                new Terrenos { Id = 39, Nome = "Chácara Serra Dourada", Area = 3600, Matricula = 3475, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis" },
                new Terrenos { Id = 40, Nome = "Fazenda Campo Grande", Area = 27000, Matricula = 8891, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande" },
                new Terrenos { Id = 41, Nome = "Sítio Vista Alegre", Area = 5200, Matricula = 2637, Proprietaria = "Vista Alegre Rural", Cidade = "Lages" },
                new Terrenos { Id = 42, Nome = "Chácara Morada do Sol", Area = 3100, Matricula = 3588, Proprietaria = "Morada Ltda", Cidade = "Araraquara" },
                new Terrenos { Id = 43, Nome = "Fazenda Santa Tereza", Area = 24000, Matricula = 8129, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá" },
                new Terrenos { Id = 44, Nome = "Sítio Recanto das Flores", Area = 4800, Matricula = 2991, Proprietaria = "Flores do Campo", Cidade = "Holambra" },
                new Terrenos { Id = 45, Nome = "Chácara Jardim das Palmeiras", Area = 3500, Matricula = 3662, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos" },
                new Terrenos { Id = 46, Nome = "Fazenda Vale do Rio", Area = 32000, Matricula = 9953, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz" },
                new Terrenos { Id = 47, Nome = "Sítio Encosta Verde", Area = 5300, Matricula = 2714, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis" },

                new Terrenos { Id = 48, Nome = "Fazenda Boa Vista", Area = 23000, Matricula = 9027, Proprietaria = "AgroSul", Cidade = "Londrina" },
                new Terrenos { Id = 49, Nome = "Sítio Bela Serra", Area = 5000, Matricula = 2841, Proprietaria = "SerraAlta", Cidade = "Guarapuava" },
                new Terrenos { Id = 50, Nome = "Chácara Vale do Sol", Area = 3600, Matricula = 3312, Proprietaria = "ValeSul", Cidade = "Ponta Grossa" },
                new Terrenos { Id = 51, Nome = "Fazenda Horizonte", Area = 25500, Matricula = 5610, Proprietaria = "TerraNova", Cidade = "Campo Grande" },
                new Terrenos { Id = 52, Nome = "Sítio Pedra Branca", Area = 6200, Matricula = 4268, Proprietaria = "PedraSul", Cidade = "Blumenau" },
                new Terrenos { Id = 53, Nome = "Chácara Primavera", Area = 3000, Matricula = 3925, Proprietaria = "Primavera Ltda", Cidade = "Florianópolis" },
                new Terrenos { Id = 54, Nome = "Fazenda Alto Alegre", Area = 21500, Matricula = 7489, Proprietaria = "Alto Agro", Cidade = "Dourados" },
                new Terrenos { Id = 55, Nome = "Sítio Campo Belo", Area = 4700, Matricula = 2971, Proprietaria = "Campo Forte", Cidade = "Uberlândia" },
                new Terrenos { Id = 56, Nome = "Chácara Estrela do Sul", Area = 3400, Matricula = 3620, Proprietaria = "Estrela Agro", Cidade = "Ribeirão Preto" },
                new Terrenos { Id = 57, Nome = "Fazenda Santa Helena", Area = 27500, Matricula = 8188, Proprietaria = "Helena Agropecuária", Cidade = "Goiânia" },
                new Terrenos { Id = 58, Nome = "Sítio Água Clara", Area = 5500, Matricula = 2793, Proprietaria = "Água Viva", Cidade = "Chapecó" },
                new Terrenos { Id = 59, Nome = "Chácara Monte Verde", Area = 4200, Matricula = 3521, Proprietaria = "Monte Verde Ltda", Cidade = "Poços de Caldas" },
                new Terrenos { Id = 60, Nome = "Fazenda Ouro Branco", Area = 30500, Matricula = 9277, Proprietaria = "Ouro Agro", Cidade = "Uberaba" },
                new Terrenos { Id = 61, Nome = "Sítio Lago Azul", Area = 4900, Matricula = 2598, Proprietaria = "Lago Azul Ltda", Cidade = "Joinville" },
                new Terrenos { Id = 62, Nome = "Chácara Boa Esperança", Area = 3200, Matricula = 3155, Proprietaria = "Esperança Rural", Cidade = "Sorocaba" },
                new Terrenos { Id = 63, Nome = "Fazenda Santa Rita", Area = 29500, Matricula = 8721, Proprietaria = "Santa Rita Agro", Cidade = "Palmas" },
                new Terrenos { Id = 64, Nome = "Sítio Encanto da Serra", Area = 5700, Matricula = 3012, Proprietaria = "Encanto Verde", Cidade = "Nova Friburgo" },
                new Terrenos { Id = 65, Nome = "Chácara Recanto Feliz", Area = 3300, Matricula = 3599, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí" },
                new Terrenos { Id = 66, Nome = "Fazenda Campo Grande", Area = 26800, Matricula = 8842, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande" },
                new Terrenos { Id = 67, Nome = "Sítio Vista Alegre", Area = 5100, Matricula = 2610, Proprietaria = "Vista Alegre Rural", Cidade = "Lages" },

                new Terrenos { Id = 68, Nome = "Fazenda Rio Dourado", Area = 22500, Matricula = 9365, Proprietaria = "Rio Agro", Cidade = "Sinop" },
                new Terrenos { Id = 69, Nome = "Sítio Bela Vista", Area = 4400, Matricula = 2798, Proprietaria = "Bela Vista Rural", Cidade = "Itu" },
                new Terrenos { Id = 70, Nome = "Chácara Sol Nascente", Area = 3800, Matricula = 3912, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas" },
                new Terrenos { Id = 71, Nome = "Fazenda Três Lagoas", Area = 28500, Matricula = 9054, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas" },
                new Terrenos { Id = 72, Nome = "Sítio Pedra Azul", Area = 5000, Matricula = 2983, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins" },
                new Terrenos { Id = 73, Nome = "Chácara Vale Encantado", Area = 3500, Matricula = 3740, Proprietaria = "Encanto Rural", Cidade = "Atibaia" },
                new Terrenos { Id = 74, Nome = "Fazenda Boa Esperança", Area = 30500, Matricula = 9802, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras" },
                new Terrenos { Id = 75, Nome = "Sítio Água Verde", Area = 4700, Matricula = 2835, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais" },
                new Terrenos { Id = 76, Nome = "Chácara Serra Dourada", Area = 3650, Matricula = 3492, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis" },
                new Terrenos { Id = 77, Nome = "Fazenda Santa Clara", Area = 26000, Matricula = 8477, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis" },
                new Terrenos { Id = 78, Nome = "Sítio Vale Verde", Area = 5200, Matricula = 2661, Proprietaria = "Vale Verde Ltda", Cidade = "Passo Fundo" },
                new Terrenos { Id = 79, Nome = "Chácara Morada do Sol", Area = 3200, Matricula = 3604, Proprietaria = "Morada Ltda", Cidade = "Araraquara" },
                new Terrenos { Id = 80, Nome = "Fazenda Santa Tereza", Area = 24500, Matricula = 8150, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá" },
                new Terrenos { Id = 81, Nome = "Sítio Recanto das Flores", Area = 4900, Matricula = 3007, Proprietaria = "Flores do Campo", Cidade = "Holambra" },
                new Terrenos { Id = 82, Nome = "Chácara Jardim das Palmeiras", Area = 3600, Matricula = 3688, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos" },
                new Terrenos { Id = 83, Nome = "Fazenda Vale do Rio", Area = 32500, Matricula = 9981, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz" },
                new Terrenos { Id = 84, Nome = "Sítio Encosta Verde", Area = 5400, Matricula = 2730, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis" },
                new Terrenos { Id = 85, Nome = "Chácara Recanto Verde", Area = 3300, Matricula = 3615, Proprietaria = "VerdeVale", Cidade = "Maringá" },
                new Terrenos { Id = 86, Nome = "Fazenda Três Rios", Area = 18200, Matricula = 6754, Proprietaria = "AgroRios", Cidade = "Cascavel" },
                new Terrenos { Id = 87, Nome = "Sítio Água Clara", Area = 5600, Matricula = 3033, Proprietaria = "Água Viva", Cidade = "Chapecó" },

                new Terrenos { Id = 88, Nome = "Fazenda Horizonte", Area = 26000, Matricula = 5638, Proprietaria = "TerraNova", Cidade = "Campo Grande" },
                new Terrenos { Id = 89, Nome = "Sítio Pedra Branca", Area = 6300, Matricula = 4285, Proprietaria = "PedraSul", Cidade = "Blumenau" },
                new Terrenos { Id = 90, Nome = "Chácara Primavera", Area = 3100, Matricula = 3950, Proprietaria = "Primavera Ltda", Cidade = "Florianópolis" },
                new Terrenos { Id = 91, Nome = "Fazenda Alto Alegre", Area = 22000, Matricula = 7521, Proprietaria = "Alto Agro", Cidade = "Dourados" },
                new Terrenos { Id = 92, Nome = "Sítio Campo Belo", Area = 4800, Matricula = 2995, Proprietaria = "Campo Forte", Cidade = "Uberlândia" },
                new Terrenos { Id = 93, Nome = "Chácara Estrela do Sul", Area = 3500, Matricula = 3641, Proprietaria = "Estrela Agro", Cidade = "Ribeirão Preto" },
                new Terrenos { Id = 94, Nome = "Fazenda Santa Helena", Area = 28000, Matricula = 8205, Proprietaria = "Helena Agropecuária", Cidade = "Goiânia" },
                new Terrenos { Id = 95, Nome = "Sítio Água Clara", Area = 5700, Matricula = 3050, Proprietaria = "Água Viva", Cidade = "Chapecó" },
                new Terrenos { Id = 96, Nome = "Chácara Monte Verde", Area = 4300, Matricula = 3544, Proprietaria = "Monte Verde Ltda", Cidade = "Poços de Caldas" },
                new Terrenos { Id = 97, Nome = "Fazenda Ouro Branco", Area = 31000, Matricula = 9302, Proprietaria = "Ouro Agro", Cidade = "Uberaba" },
                new Terrenos { Id = 98, Nome = "Sítio Lago Azul", Area = 5000, Matricula = 2620, Proprietaria = "Lago Azul Ltda", Cidade = "Joinville" },
                new Terrenos { Id = 99, Nome = "Chácara Boa Esperança", Area = 3400, Matricula = 3180, Proprietaria = "Esperança Rural", Cidade = "Sorocaba" },
                new Terrenos { Id = 100, Nome = "Fazenda Santa Rita", Area = 30000, Matricula = 8750, Proprietaria = "Santa Rita Agro", Cidade = "Palmas" },
                new Terrenos { Id = 101, Nome = "Sítio Encanto da Serra", Area = 5800, Matricula = 3072, Proprietaria = "Encanto Verde", Cidade = "Nova Friburgo" },
                new Terrenos { Id = 102, Nome = "Chácara Recanto Feliz", Area = 3500, Matricula = 3628, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí" },
                new Terrenos { Id = 103, Nome = "Fazenda Campo Grande", Area = 27500, Matricula = 8870, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande" },
                new Terrenos { Id = 104, Nome = "Sítio Vista Alegre", Area = 5200, Matricula = 2630, Proprietaria = "Vista Alegre Rural", Cidade = "Lages" },
                new Terrenos { Id = 105, Nome = "Chácara Morada do Sol", Area = 3300, Matricula = 3639, Proprietaria = "Morada Ltda", Cidade = "Araraquara" },
                new Terrenos { Id = 106, Nome = "Fazenda Santa Tereza", Area = 25000, Matricula = 8182, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá" },
                new Terrenos { Id = 107, Nome = "Sítio Recanto das Flores", Area = 5000, Matricula = 3095, Proprietaria = "Flores do Campo", Cidade = "Holambra" },

                new Terrenos { Id = 108, Nome = "Fazenda Boa Vista", Area = 24000, Matricula = 9842, Proprietaria = "AgroSul", Cidade = "Londrina" },
                new Terrenos { Id = 109, Nome = "Sítio Bela Serra", Area = 5100, Matricula = 2888, Proprietaria = "SerraAlta", Cidade = "Guarapuava" },
                new Terrenos { Id = 110, Nome = "Chácara Vale do Sol", Area = 3700, Matricula = 3360, Proprietaria = "ValeSul", Cidade = "Ponta Grossa" },
                new Terrenos { Id = 111, Nome = "Fazenda Horizonte", Area = 26500, Matricula = 5689, Proprietaria = "TerraNova", Cidade = "Campo Grande" },
                new Terrenos { Id = 112, Nome = "Sítio Pedra Branca", Area = 6400, Matricula = 4310, Proprietaria = "PedraSul", Cidade = "Blumenau" },
                new Terrenos { Id = 113, Nome = "Chácara Primavera", Area = 3200, Matricula = 3982, Proprietaria = "Primavera Ltda", Cidade = "Florianópolis" },
                new Terrenos { Id = 114, Nome = "Fazenda Alto Alegre", Area = 22500, Matricula = 7560, Proprietaria = "Alto Agro", Cidade = "Dourados" },
                new Terrenos { Id = 115, Nome = "Sítio Campo Belo", Area = 4900, Matricula = 3011, Proprietaria = "Campo Forte", Cidade = "Uberlândia" },
                new Terrenos { Id = 116, Nome = "Chácara Estrela do Sul", Area = 3600, Matricula = 3678, Proprietaria = "Estrela Agro", Cidade = "Ribeirão Preto" },
                new Terrenos { Id = 117, Nome = "Fazenda Santa Helena", Area = 28500, Matricula = 8239, Proprietaria = "Helena Agropecuária", Cidade = "Goiânia" },
                new Terrenos { Id = 118, Nome = "Sítio Água Clara", Area = 5800, Matricula = 3108, Proprietaria = "Água Viva", Cidade = "Chapecó" },
                new Terrenos { Id = 119, Nome = "Chácara Monte Verde", Area = 4400, Matricula = 3570, Proprietaria = "Monte Verde Ltda", Cidade = "Poços de Caldas" },
                new Terrenos { Id = 120, Nome = "Fazenda Ouro Branco", Area = 31500, Matricula = 9350, Proprietaria = "Ouro Agro", Cidade = "Uberaba" },
                new Terrenos { Id = 121, Nome = "Sítio Lago Azul", Area = 5100, Matricula = 2655, Proprietaria = "Lago Azul Ltda", Cidade = "Joinville" },
                new Terrenos { Id = 122, Nome = "Chácara Boa Esperança", Area = 3500, Matricula = 3202, Proprietaria = "Esperança Rural", Cidade = "Sorocaba" },
                new Terrenos { Id = 123, Nome = "Fazenda Santa Rita", Area = 30500, Matricula = 8799, Proprietaria = "Santa Rita Agro", Cidade = "Palmas" },
                new Terrenos { Id = 124, Nome = "Sítio Encanto da Serra", Area = 5900, Matricula = 3125, Proprietaria = "Encanto Verde", Cidade = "Nova Friburgo" },
                new Terrenos { Id = 125, Nome = "Chácara Recanto Feliz", Area = 3600, Matricula = 3666, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí" },
                new Terrenos { Id = 126, Nome = "Fazenda Campo Grande", Area = 28000, Matricula = 8915, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande" },
                new Terrenos { Id = 127, Nome = "Sítio Vista Alegre", Area = 5300, Matricula = 2668, Proprietaria = "Vista Alegre Rural", Cidade = "Lages" },

                new Terrenos { Id = 128, Nome = "Chácara Morada do Sol", Area = 3400, Matricula = 3695, Proprietaria = "Morada Ltda", Cidade = "Araraquara" },
                new Terrenos { Id = 129, Nome = "Fazenda Santa Tereza", Area = 25500, Matricula = 8221, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá" },
                new Terrenos { Id = 130, Nome = "Sítio Recanto das Flores", Area = 5100, Matricula = 3133, Proprietaria = "Flores do Campo", Cidade = "Holambra" },
                new Terrenos { Id = 131, Nome = "Chácara Jardim das Palmeiras", Area = 3700, Matricula = 3710, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos" },
                new Terrenos { Id = 132, Nome = "Fazenda Vale do Rio", Area = 33000, Matricula = 10012, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz" },
                new Terrenos { Id = 133, Nome = "Sítio Encosta Verde", Area = 5500, Matricula = 2755, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis" },
                new Terrenos { Id = 134, Nome = "Chácara Recanto Verde", Area = 3400, Matricula = 3640, Proprietaria = "VerdeVale", Cidade = "Maringá" },
                new Terrenos { Id = 135, Nome = "Fazenda Três Rios", Area = 18500, Matricula = 6788, Proprietaria = "AgroRios", Cidade = "Cascavel" },
                new Terrenos { Id = 136, Nome = "Sítio Água Clara", Area = 6000, Matricula = 3159, Proprietaria = "Água Viva", Cidade = "Chapecó" },
                new Terrenos { Id = 137, Nome = "Chácara Sol Nascente", Area = 3900, Matricula = 3935, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas" },
                new Terrenos { Id = 138, Nome = "Fazenda Três Lagoas", Area = 29000, Matricula = 9089, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas" },
                new Terrenos { Id = 139, Nome = "Sítio Pedra Azul", Area = 5200, Matricula = 3008, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins" },
                new Terrenos { Id = 140, Nome = "Chácara Vale Encantado", Area = 3600, Matricula = 3762, Proprietaria = "Encanto Rural", Cidade = "Atibaia" },
                new Terrenos { Id = 141, Nome = "Fazenda Boa Esperança", Area = 31000, Matricula = 9833, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras" },
                new Terrenos { Id = 142, Nome = "Sítio Água Verde", Area = 4800, Matricula = 2860, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais" },
                new Terrenos { Id = 143, Nome = "Chácara Serra Dourada", Area = 3700, Matricula = 3515, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis" },
                new Terrenos { Id = 144, Nome = "Fazenda Santa Clara", Area = 26500, Matricula = 8505, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis" },
                new Terrenos { Id = 145, Nome = "Sítio Vale Verde", Area = 5300, Matricula = 2689, Proprietaria = "Vale Verde Ltda", Cidade = "Passo Fundo" },
                new Terrenos { Id = 146, Nome = "Chácara Recanto Feliz", Area = 3700, Matricula = 3685, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí" },
                new Terrenos { Id = 147, Nome = "Fazenda Campo Grande", Area = 28500, Matricula = 8950, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande" },

                new Terrenos { Id = 148, Nome = "Sítio Vista Alegre", Area = 5400, Matricula = 2705, Proprietaria = "Vista Alegre Rural", Cidade = "Lages" },
                new Terrenos { Id = 149, Nome = "Chácara Morada do Sol", Area = 3500, Matricula = 3728, Proprietaria = "Morada Ltda", Cidade = "Araraquara" },
                new Terrenos { Id = 150, Nome = "Fazenda Santa Tereza", Area = 26000, Matricula = 8254, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá" },
                new Terrenos { Id = 151, Nome = "Sítio Recanto das Flores", Area = 5200, Matricula = 3167, Proprietaria = "Flores do Campo", Cidade = "Holambra" },
                new Terrenos { Id = 152, Nome = "Chácara Jardim das Palmeiras", Area = 3800, Matricula = 3739, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos" },
                new Terrenos { Id = 153, Nome = "Fazenda Vale do Rio", Area = 33500, Matricula = 10045, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz" },
                new Terrenos { Id = 154, Nome = "Sítio Encosta Verde", Area = 5600, Matricula = 2780, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis" },
                new Terrenos { Id = 155, Nome = "Chácara Recanto Verde", Area = 3500, Matricula = 3661, Proprietaria = "VerdeVale", Cidade = "Maringá" },
                new Terrenos { Id = 156, Nome = "Fazenda Três Rios", Area = 19000, Matricula = 6812, Proprietaria = "AgroRios", Cidade = "Cascavel" },
                new Terrenos { Id = 157, Nome = "Sítio Água Clara", Area = 6100, Matricula = 3184, Proprietaria = "Água Viva", Cidade = "Chapecó" },
                new Terrenos { Id = 158, Nome = "Chácara Sol Nascente", Area = 4000, Matricula = 3960, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas" },
                new Terrenos { Id = 159, Nome = "Fazenda Três Lagoas", Area = 29500, Matricula = 9120, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas" },
                new Terrenos { Id = 160, Nome = "Sítio Pedra Azul", Area = 5300, Matricula = 3035, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins" },
                new Terrenos { Id = 161, Nome = "Chácara Vale Encantado", Area = 3700, Matricula = 3788, Proprietaria = "Encanto Rural", Cidade = "Atibaia" },
                new Terrenos { Id = 162, Nome = "Fazenda Boa Esperança", Area = 31500, Matricula = 9860, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras" },
                new Terrenos { Id = 163, Nome = "Sítio Água Verde", Area = 4900, Matricula = 2884, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais" },
                new Terrenos { Id = 164, Nome = "Chácara Serra Dourada", Area = 3800, Matricula = 3540, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis" },
                new Terrenos { Id = 165, Nome = "Fazenda Santa Clara", Area = 27000, Matricula = 8533, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis" },
                new Terrenos { Id = 166, Nome = "Sítio Vale Verde", Area = 5400, Matricula = 2715, Proprietaria = "Vale Verde Ltda", Cidade = "Passo Fundo" },
                new Terrenos { Id = 167, Nome = "Chácara Recanto Feliz", Area = 3800, Matricula = 3709, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí" },

                new Terrenos { Id = 168, Nome = "Fazenda Campo Grande", Area = 29000, Matricula = 8982, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande" },
                new Terrenos { Id = 169, Nome = "Sítio Vista Alegre", Area = 5500, Matricula = 2738, Proprietaria = "Vista Alegre Rural", Cidade = "Lages" },
                new Terrenos { Id = 170, Nome = "Chácara Morada do Sol", Area = 3600, Matricula = 3756, Proprietaria = "Morada Ltda", Cidade = "Araraquara" },
                new Terrenos { Id = 171, Nome = "Fazenda Santa Tereza", Area = 26500, Matricula = 8289, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá" },
                new Terrenos { Id = 172, Nome = "Sítio Recanto das Flores", Area = 5300, Matricula = 3199, Proprietaria = "Flores do Campo", Cidade = "Holambra" },
                new Terrenos { Id = 173, Nome = "Chácara Jardim das Palmeiras", Area = 3900, Matricula = 3768, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos" },
                new Terrenos { Id = 174, Nome = "Fazenda Vale do Rio", Area = 34000, Matricula = 10078, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz" },
                new Terrenos { Id = 175, Nome = "Sítio Encosta Verde", Area = 5700, Matricula = 2804, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis" },
                new Terrenos { Id = 176, Nome = "Chácara Recanto Verde", Area = 3600, Matricula = 3684, Proprietaria = "VerdeVale", Cidade = "Maringá" },
                new Terrenos { Id = 177, Nome = "Fazenda Três Rios", Area = 19500, Matricula = 6845, Proprietaria = "AgroRios", Cidade = "Cascavel" },
                new Terrenos { Id = 178, Nome = "Sítio Água Clara", Area = 6200, Matricula = 3210, Proprietaria = "Água Viva", Cidade = "Chapecó" },
                new Terrenos { Id = 179, Nome = "Chácara Sol Nascente", Area = 4100, Matricula = 3987, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas" },
                new Terrenos { Id = 180, Nome = "Fazenda Três Lagoas", Area = 30000, Matricula = 9156, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas" },
                new Terrenos { Id = 181, Nome = "Sítio Pedra Azul", Area = 5400, Matricula = 3062, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins" },
                new Terrenos { Id = 182, Nome = "Chácara Vale Encantado", Area = 3800, Matricula = 3815, Proprietaria = "Encanto Rural", Cidade = "Atibaia" },
                new Terrenos { Id = 183, Nome = "Fazenda Boa Esperança", Area = 32000, Matricula = 9894, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras" },
                new Terrenos { Id = 184, Nome = "Sítio Água Verde", Area = 5000, Matricula = 2907, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais" },
                new Terrenos { Id = 185, Nome = "Chácara Serra Dourada", Area = 3900, Matricula = 3566, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis" },
                new Terrenos { Id = 186, Nome = "Fazenda Santa Clara", Area = 27500, Matricula = 8570, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis" },
                new Terrenos { Id = 187, Nome = "Sítio Vale Verde", Area = 5500, Matricula = 2742, Proprietaria = "Vale Verde Ltda", Cidade = "Passo Fundo" },

                new Terrenos { Id = 188, Nome = "Chácara Recanto Feliz", Area = 3900, Matricula = 3735, Proprietaria = "Recanto Ltda", Cidade = "Jundiaí" },
                new Terrenos { Id = 189, Nome = "Fazenda Campo Grande", Area = 29500, Matricula = 9010, Proprietaria = "Campo Grande Agro", Cidade = "Campo Grande" },
                new Terrenos { Id = 190, Nome = "Sítio Vista Alegre", Area = 5600, Matricula = 2766, Proprietaria = "Vista Alegre Rural", Cidade = "Lages" },
                new Terrenos { Id = 191, Nome = "Chácara Morada do Sol", Area = 3700, Matricula = 3780, Proprietaria = "Morada Ltda", Cidade = "Araraquara" },
                new Terrenos { Id = 192, Nome = "Fazenda Santa Tereza", Area = 27000, Matricula = 8320, Proprietaria = "Santa Tereza Agro", Cidade = "Cuiabá" },
                new Terrenos { Id = 193, Nome = "Sítio Recanto das Flores", Area = 5400, Matricula = 3228, Proprietaria = "Flores do Campo", Cidade = "Holambra" },
                new Terrenos { Id = 194, Nome = "Chácara Jardim das Palmeiras", Area = 4000, Matricula = 3799, Proprietaria = "Palmeiras Ltda", Cidade = "São Carlos" },
                new Terrenos { Id = 195, Nome = "Fazenda Vale do Rio", Area = 34500, Matricula = 10105, Proprietaria = "Vale do Rio Agro", Cidade = "Imperatriz" },
                new Terrenos { Id = 196, Nome = "Sítio Encosta Verde", Area = 5800, Matricula = 2831, Proprietaria = "Encosta Ltda", Cidade = "Petrópolis" },
                new Terrenos { Id = 197, Nome = "Chácara Recanto Verde", Area = 3700, Matricula = 3702, Proprietaria = "VerdeVale", Cidade = "Maringá" },
                new Terrenos { Id = 198, Nome = "Fazenda Três Rios", Area = 20000, Matricula = 6879, Proprietaria = "AgroRios", Cidade = "Cascavel" },
                new Terrenos { Id = 199, Nome = "Sítio Água Clara", Area = 6300, Matricula = 3244, Proprietaria = "Água Viva", Cidade = "Chapecó" },
                new Terrenos { Id = 200, Nome = "Chácara Sol Nascente", Area = 4200, Matricula = 4012, Proprietaria = "Sol Nascente Agro", Cidade = "Campinas" },
                new Terrenos { Id = 201, Nome = "Fazenda Três Lagoas", Area = 30500, Matricula = 9188, Proprietaria = "Lagoas Agro", Cidade = "Três Lagoas" },
                new Terrenos { Id = 202, Nome = "Sítio Pedra Azul", Area = 5500, Matricula = 3089, Proprietaria = "Pedra Azul Ltda", Cidade = "Domingos Martins" },
                new Terrenos { Id = 203, Nome = "Chácara Vale Encantado", Area = 3900, Matricula = 3840, Proprietaria = "Encanto Rural", Cidade = "Atibaia" },
                new Terrenos { Id = 204, Nome = "Fazenda Boa Esperança", Area = 32500, Matricula = 9925, Proprietaria = "Boa Esperança Agro", Cidade = "Barreiras" },
                new Terrenos { Id = 205, Nome = "Sítio Água Verde", Area = 5100, Matricula = 2930, Proprietaria = "Água Verde Ltda", Cidade = "São José dos Pinhais" },
                new Terrenos { Id = 206, Nome = "Chácara Serra Dourada", Area = 4000, Matricula = 3592, Proprietaria = "Serra Dourada Agro", Cidade = "Anápolis" },
                new Terrenos { Id = 207, Nome = "Fazenda Santa Clara", Area = 28000, Matricula = 8602, Proprietaria = "Santa Clara Agro", Cidade = "Rondonópolis" }

                );
        }
    }
}

